package client;

import javax.xml.ws.WebFault;

@WebFault(faultBean="genJava.Exception", targetNamespace="http://ifs.integration.eq.qantas/",
  name="Exception")
public class Exception
  extends java.lang.Exception
{
  private genJava.Exception faultInfo;

  public Exception(String message, genJava.Exception faultInfo)
  {
    super(message);
    this.faultInfo = faultInfo;
  }

  public Exception(String message, genJava.Exception faultInfo,
                   Throwable t)
  {
    super(message,t);
    this.faultInfo = faultInfo;
  }

  public genJava.Exception getFaultInfo()
  {
    return faultInfo;
  }

  public void setFaultInfo(genJava.Exception faultInfo)
  {
    this.faultInfo = faultInfo;
  }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)
