
package qantas.imaging.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ImagingServiceImpl", targetNamespace = "http://webService.imaging.qantas/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ImagingServiceImpl {


    /**
     * 
     * @param deleteFlag
     * @param renameFilename
     * @param wccPath
     * @param errorMessage
     * @param ifId
     * @param srcFileName
     * @param ipmID
     * @param srcFilePath
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateService", targetNamespace = "http://webService.imaging.qantas/", className = "qantas.imaging.webservice.UpdateService")
    @ResponseWrapper(localName = "updateServiceResponse", targetNamespace = "http://webService.imaging.qantas/", className = "qantas.imaging.webservice.UpdateServiceResponse")
    public String updateService(
        @WebParam(name = "IPM_ID", targetNamespace = "")
        String ipmID,
        @WebParam(name = "IF_id", targetNamespace = "")
        String ifId,
        @WebParam(name = "Src_File_Path", targetNamespace = "")
        String srcFilePath,
        @WebParam(name = "Src_File_Name", targetNamespace = "")
        String srcFileName,
        @WebParam(name = "DeleteFlag", targetNamespace = "")
        String deleteFlag,
        @WebParam(name = "rename_filename", targetNamespace = "")
        String renameFilename,
        @WebParam(name = "wcc_path", targetNamespace = "")
        String wccPath,
        @WebParam(name = "Error_message", targetNamespace = "")
        String errorMessage)
        throws Exception_Exception
    ;

    /**
     * 
     * @param renameFilename
     * @param deleteFlag
     * @param fileName
     * @param wccPath
     * @param filePath
     * @param errorMessage
     * @param ifId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadFile", targetNamespace = "http://webService.imaging.qantas/", className = "qantas.imaging.webservice.UploadFile")
    @ResponseWrapper(localName = "uploadFileResponse", targetNamespace = "http://webService.imaging.qantas/", className = "qantas.imaging.webservice.UploadFileResponse")
    public String uploadFile(
        @WebParam(name = "IF_id", targetNamespace = "")
        String ifId,
        @WebParam(name = "File_Path", targetNamespace = "")
        String filePath,
        @WebParam(name = "File_Name", targetNamespace = "")
        String fileName,
        @WebParam(name = "wcc_Path", targetNamespace = "")
        String wccPath,
        @WebParam(name = "rename_filename", targetNamespace = "")
        String renameFilename,
        @WebParam(name = "Error_message", targetNamespace = "")
        String errorMessage,
        @WebParam(name = "Delete_Flag", targetNamespace = "")
        String deleteFlag);

    /**
     * 
     * @param renameFilename
     * @param ifId
     * @param srcFileName
     * @param srcFilePath
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchIPM", targetNamespace = "http://webService.imaging.qantas/", className = "qantas.imaging.webservice.SearchIPM")
    @ResponseWrapper(localName = "searchIPMResponse", targetNamespace = "http://webService.imaging.qantas/", className = "qantas.imaging.webservice.SearchIPMResponse")
    public List<String> searchIPM(
        @WebParam(name = "IF_id", targetNamespace = "")
        String ifId,
        @WebParam(name = "Src_File_Path", targetNamespace = "")
        String srcFilePath,
        @WebParam(name = "Src_File_Name", targetNamespace = "")
        String srcFileName,
        @WebParam(name = "rename_filename", targetNamespace = "")
        String renameFilename);

}
