package model;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 14 17:02:09 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EbsAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EbsAMImpl() {
    }

    /**
     * Container's getter for SitesVO1.
     * @return SitesVO1
     */
    public SitesVOImpl getSitesVO1() {
        return (SitesVOImpl)findViewObject("SitesVO1");
    }

    /**
     * Container's getter for ProjectVO1.
     * @return ProjectVO1
     */
    public ProjectVOImpl getProjectVO1() {
        return (ProjectVOImpl)findViewObject("ProjectVO1");
    }

    /**
     * Container's getter for ExpenditureVO1.
     * @return ExpenditureVO1
     */
    public ExpenditureVOImpl getExpenditureVO1() {
        return (ExpenditureVOImpl)findViewObject("ExpenditureVO1");
    }

    /**
     * Container's getter for CertifierVO1.
     * @return CertifierVO1
     */
    public CertifierVOImpl getCertifierVO1() {
        return (CertifierVOImpl)findViewObject("CertifierVO1");
    }

    /**
     * Container's getter for HeaderLineVO1.
     * @return HeaderLineVO1
     */
    public HeaderLineVOImpl getHeaderLineVO1() {
        return (HeaderLineVOImpl)findViewObject("HeaderLineVO1");
    }

    /**
     * Container's getter for SitesDetailsVO1.
     * @return SitesDetailsVO1
     */
    public ViewObjectImpl getSitesDetailsVO1() {
        return (ViewObjectImpl)findViewObject("SitesDetailsVO1");
    }

    /**
     * Container's getter for POVO1.
     * @return POVO1
     */
    public POVOImpl getPOVO1() {
        return (POVOImpl)findViewObject("POVO1");
    }


    /**
     * Container's getter for GetMaxLineNumberVO1.
     * @return GetMaxLineNumberVO1
     */
    public ViewObjectImpl getGetMaxLineNumberVO1() {
        return (ViewObjectImpl)findViewObject("GetMaxLineNumberVO1");
    }

    /**
     * Container's getter for HeaderDetailsEOView1.
     * @return HeaderDetailsEOView1
     */
    public ViewObjectImpl getHeaderDetailsEOView1() {
        return (ViewObjectImpl)findViewObject("HeaderDetailsEOView1");
    }

    /**
     * Container's getter for LineItemDetailsEOView1.
     * @return LineItemDetailsEOView1
     */
    public ViewObjectImpl getLineItemDetailsEOView1() {
        return (ViewObjectImpl)findViewObject("LineItemDetailsEOView1");
    }

    /**
     * Container's getter for ExpenditureOrgVO1.
     * @return ExpenditureOrgVO1
     */
    public ViewObjectImpl getExpenditureOrgVO1() {
        return (ViewObjectImpl)findViewObject("ExpenditureOrgVO1");
    }

    /**
     * Container's getter for CertProjectTaskExpdDetailsVO1.
     * @return CertProjectTaskExpdDetailsVO1
     */
    public ViewObjectImpl getCertProjectTaskExpdDetailsVO1() {
        return (ViewObjectImpl)findViewObject("CertProjectTaskExpdDetailsVO1");
    }

    /**
     * Container's getter for TaxRateCodeVO1.
     * @return TaxRateCodeVO1
     */
    public ViewObjectImpl getTaxRateCodeVO1() {
        return (ViewObjectImpl)findViewObject("TaxRateCodeVO1");
    }


    /**
     * Container's getter for POLineDetailsVO1.
     * @return POLineDetailsVO1
     */
    public ViewObjectImpl getPOLineDetailsVO1() {
        return (ViewObjectImpl)findViewObject("POLineDetailsVO1");
    }

    /**
     * Container's getter for CurrencyCodeVO1.
     * @return CurrencyCodeVO1
     */
    public ViewObjectImpl getCurrencyCodeVO1() {
        return (ViewObjectImpl)findViewObject("CurrencyCodeVO1");
    }

    /**
     * Container's getter for CertifierNameVO1.
     * @return CertifierNameVO1
     */
    public ViewObjectImpl getCertifierNameVO1() {
        return (ViewObjectImpl)findViewObject("CertifierNameVO1");
    }

    /**
     * Container's getter for TaxRateCodeLookupVO1.
     * @return TaxRateCodeLookupVO1
     */
    public ViewObjectImpl getTaxRateCodeLookupVO1() {
        return (ViewObjectImpl)findViewObject("TaxRateCodeLookupVO1");
    }
    /*
     * Container's getter for AccountVO1.
     * @return AccountVO1
     */
    public ViewObjectImpl getAccountVO1() {
        return (ViewObjectImpl)findViewObject("AccountVO1");
    }

    /**
     * Container's getter for AnalysisCodeVO1.
     * @return AnalysisCodeVO1
     */
    public ViewObjectImpl getAnalysisCodeVO1() {
        return (ViewObjectImpl)findViewObject("AnalysisCodeVO1");
    }

    /**
     * Container's getter for CompanyCounterPartyVO1.
     * @return CompanyCounterPartyVO1
     */
    public ViewObjectImpl getCompanyCounterPartyVO1() {
        return (ViewObjectImpl)findViewObject("CompanyCounterPartyVO1");
    }

    /**
     * Container's getter for CostCentreVO1.
     * @return CostCentreVO1
     */
    public ViewObjectImpl getCostCentreVO1() {
        return (ViewObjectImpl)findViewObject("CostCentreVO1");
    }

    /**
     * Container's getter for POLineNumberDetailsVO1.
     * @return POLineNumberDetailsVO1
     */
    public ViewObjectImpl getPOLineNumberDetailsVO1() {
        return (ViewObjectImpl)findViewObject("POLineNumberDetailsVO1");
    }

    /**
     * Container's getter for TaskNumberVO1.
     * @return TaskNumberVO1
     */
    public ViewObjectImpl getTaskNumberVO1() {
        return (ViewObjectImpl)findViewObject("TaskNumberVO1");
    }


    /**
     * Container's getter for ValidateGLCodeVO1.
     * @return ValidateGLCodeVO1
     */
    public ViewObjectImpl getValidateGLCodeVO1() {
        return (ViewObjectImpl)findViewObject("ValidateGLCodeVO1");
    }

    /**
     * Container's getter for PoNoCertifierVO1.
     * @return PoNoCertifierVO1
     */
    public ViewObjectImpl getPoNoCertifierVO1() {
        return (ViewObjectImpl)findViewObject("PoNoCertifierVO1");
    }

    /**
     * Container's getter for CertifierNameVO_ActiveOnlyRecords1.
     * @return CertifierNameVO_ActiveOnlyRecords1
     */
    public ViewObjectImpl getCertifierNameVO_ActiveOnlyRecords1() {
        return (ViewObjectImpl)findViewObject("CertifierNameVO_ActiveOnlyRecords1");
    }

    /**
     * Container's getter for TaxRateCodeMasterListVO1.
     * @return TaxRateCodeMasterListVO1
     */
    public ViewObjectImpl getTaxRateCodeMasterListVO1() {
        return (ViewObjectImpl)findViewObject("TaxRateCodeMasterListVO1");
    }

    /**
     * Container's getter for searchCertifierVO1.
     * @return searchCertifierVO1
     */
    public ViewObjectImpl getsearchCertifierVO1() {
        return (ViewObjectImpl)findViewObject("searchCertifierVO1");
    }

    /**
     * Container's getter for ProjectNumberVO1.
     * @return ProjectNumberVO1
     */
    public ViewObjectImpl getProjectNumberVO1() {
        return (ViewObjectImpl)findViewObject("ProjectNumberVO1");
    }

    /**
     * Container's getter for ExpenditureDateVO1.
     * @return ExpenditureDateVO1
     */
    public ViewObjectImpl getExpenditureDateVO1() {
        return (ViewObjectImpl)findViewObject("ExpenditureDateVO1");
    }

    /**
     * Container's getter for ExpenditureTypeVO1.
     * @return ExpenditureTypeVO1
     */
    public ViewObjectImpl getExpenditureTypeVO1() {
        return (ViewObjectImpl)findViewObject("ExpenditureTypeVO1");
    }
}
