package model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 14 16:06:59 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SitesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SitesVOImpl() {
    }


    /**
     * Returns the variable value for bindVendorName.
     * @return variable value for bindVendorName
     */
    public String getbindVendorName() {
        return (String)ensureVariableManager().getVariableValue("bindVendorName");
    }

    /**
     * Sets <code>value</code> for variable bindVendorName.
     * @param value value to bind as bindVendorName
     */
    public void setbindVendorName(String value) {
        ensureVariableManager().setVariableValue("bindVendorName", value);
    }

    /**
     * Returns the variable value for bvSiteID.
     * @return variable value for bvSiteID
     */
    public String getbvSiteID() {
        return (String)ensureVariableManager().getVariableValue("bvSiteID");
    }

    /**
     * Sets <code>value</code> for variable bvSiteID.
     * @param value value to bind as bvSiteID
     */
    public void setbvSiteID(String value) {
        ensureVariableManager().setVariableValue("bvSiteID", value);
    }

    /**
     * Returns the bind variable value for bindOperatingUnit.
     * @return bind variable value for bindOperatingUnit
     */
    public String getbindOperatingUnit() {
        return (String)getNamedWhereClauseParam("bindOperatingUnit");
    }

    /**
     * Sets <code>value</code> for bind variable bindOperatingUnit.
     * @param value value to bind as bindOperatingUnit
     */
    public void setbindOperatingUnit(String value) {
        setNamedWhereClauseParam("bindOperatingUnit", value);
    }
}
