
package src.com;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CommonNotification", targetNamespace = "http://com.src/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CommonNotification {


    /**
     * 
     * @param mailSubject
     * @param mailBody
     * @param ifId
     * @param mailToAddress
     * @param mailCcAddress
     * @param mailFromAddress
     * @param mailBccAddress
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "commonNotificationDetails", targetNamespace = "http://com.src/", className = "src.com.CommonNotificationDetails")
    public void commonNotificationDetails(
        @WebParam(name = "IFId", targetNamespace = "http://com.src/")
        String ifId,
        @WebParam(name = "mailToAddress", targetNamespace = "http://com.src/")
        String mailToAddress,
        @WebParam(name = "mailBody", targetNamespace = "http://com.src/")
        String mailBody,
        @WebParam(name = "mailSubject", targetNamespace = "http://com.src/")
        String mailSubject,
        @WebParam(name = "mailCcAddress", targetNamespace = "http://com.src/")
        String mailCcAddress,
        @WebParam(name = "mailBccAddress", targetNamespace = "http://com.src/")
        String mailBccAddress,
        @WebParam(name = "mailFromAddress", targetNamespace = "http://com.src/")
        String mailFromAddress);

}
