
package src.com;

import java.io.FileInputStream;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "QantasCommonNotificationService", targetNamespace = "http://com.src/", wsdlLocation = "http://eqosb.qantas.com.au/CommonNotificationProject/ProxyService/CommonNotificationSevice_PS?wsdl")
public class QantasCommonNotificationService
    extends Service
{

    private final static URL QANTASCOMMONNOTIFICATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException QANTASCOMMONNOTIFICATIONSERVICE_EXCEPTION;
    private final static QName QANTASCOMMONNOTIFICATIONSERVICE_QNAME = new QName("http://com.src/", "QantasCommonNotificationService");
    private static Logger logger;
    static {
        URL url = null;
        WebServiceException ex = null;
        Properties pro = new Properties();
        try {
        	String configFile = System.getenv("QFEQIF_CONFIG");
            pro.load(new FileInputStream(configFile));
            logger = Logger.getLogger("email.notification.client.QantasCommonNotificationService");
            //url = new URL("http://eqosbsit.qantas.com.au/CommonNotificationProject/ProxyService/CommonNotificationSevice_PS?wsdl");
            url = new URL(pro.getProperty("COMMON_NOTIFICATION_URL"));
        } 
        catch (Exception e)
        {
          logger.log(Level.ALL,
              "Failed to create wsdlLocationURL using "  + pro.getProperty("COMMON_NOTIFICATION_URL"),
              e);
        }
        QANTASCOMMONNOTIFICATIONSERVICE_WSDL_LOCATION = url;
        QANTASCOMMONNOTIFICATIONSERVICE_EXCEPTION = ex;
    }

    public QantasCommonNotificationService() {
        super(__getWsdlLocation(), QANTASCOMMONNOTIFICATIONSERVICE_QNAME);
    }

    public QantasCommonNotificationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), QANTASCOMMONNOTIFICATIONSERVICE_QNAME, features);
    }

    public QantasCommonNotificationService(URL wsdlLocation) {
        super(wsdlLocation, QANTASCOMMONNOTIFICATIONSERVICE_QNAME);
    }

    public QantasCommonNotificationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QANTASCOMMONNOTIFICATIONSERVICE_QNAME, features);
    }

    public QantasCommonNotificationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QantasCommonNotificationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CommonNotification
     */
    @WebEndpoint(name = "CommonNotificationPort")
    public CommonNotification getCommonNotificationPort() {
        return super.getPort(new QName("http://com.src/", "CommonNotificationPort"), CommonNotification.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommonNotification
     */
    @WebEndpoint(name = "CommonNotificationPort")
    public CommonNotification getCommonNotificationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com.src/", "CommonNotificationPort"), CommonNotification.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QANTASCOMMONNOTIFICATIONSERVICE_EXCEPTION!= null) {
            throw QANTASCOMMONNOTIFICATIONSERVICE_EXCEPTION;
        }
        return QANTASCOMMONNOTIFICATIONSERVICE_WSDL_LOCATION;
    }

}
