
package ap.quantas.com.bamUpdateWebService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DataObjectOperationsByID", targetNamespace = "http://xmlns.oracle.com/bam")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DataObjectOperationsByID {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "destroy", targetNamespace = "http://xmlns.oracle.com/bam", className = "ap.quantas.com.bamUpdateWebService.Destroy")
    @ResponseWrapper(localName = "destroyResponse", targetNamespace = "http://xmlns.oracle.com/bam", className = "ap.quantas.com.bamUpdateWebService.DestroyResponse")
    public void destroy();

    /**
     * 
     * @param keysCSV
     * @param xmlPayload
     * @param dataObject
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Delete", action = "http://xmlns.oracle.com/bam/Delete")
    @WebResult(name = "DeleteResult", targetNamespace = "http://xmlns.oracle.com/bam")
    @RequestWrapper(localName = "Delete", targetNamespace = "http://xmlns.oracle.com/bam", className = "ap.quantas.com.bamUpdateWebService.Delete")
    @ResponseWrapper(localName = "DeleteResponse", targetNamespace = "http://xmlns.oracle.com/bam", className = "ap.quantas.com.bamUpdateWebService.DeleteResponse")
    public boolean delete(
        @WebParam(name = "dataObject", targetNamespace = "http://xmlns.oracle.com/bam")
        String dataObject,
        @WebParam(name = "keysCSV", targetNamespace = "http://xmlns.oracle.com/bam")
        String keysCSV,
        @WebParam(name = "xmlPayload", targetNamespace = "http://xmlns.oracle.com/bam")
        String xmlPayload);

    /**
     * 
     * @param xmlPayload
     * @param dataObject
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Insert", action = "http://xmlns.oracle.com/bam/Insert")
    @WebResult(name = "InsertResult", targetNamespace = "http://xmlns.oracle.com/bam")
    @RequestWrapper(localName = "Insert", targetNamespace = "http://xmlns.oracle.com/bam", className = "ap.quantas.com.bamUpdateWebService.Insert")
    @ResponseWrapper(localName = "InsertResponse", targetNamespace = "http://xmlns.oracle.com/bam", className = "ap.quantas.com.bamUpdateWebService.InsertResponse")
    public boolean insert(
        @WebParam(name = "dataObject", targetNamespace = "http://xmlns.oracle.com/bam")
        String dataObject,
        @WebParam(name = "xmlPayload", targetNamespace = "http://xmlns.oracle.com/bam")
        String xmlPayload);

    /**
     * 
     * @param keysCSV
     * @param xmlPayload
     * @param dataObject
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Update", action = "http://xmlns.oracle.com/bam/Update")
    @WebResult(name = "UpdateResult", targetNamespace = "http://xmlns.oracle.com/bam")
    @RequestWrapper(localName = "Update", targetNamespace = "http://xmlns.oracle.com/bam", className = "ap.quantas.com.bamUpdateWebService.Update")
    @ResponseWrapper(localName = "UpdateResponse", targetNamespace = "http://xmlns.oracle.com/bam", className = "ap.quantas.com.bamUpdateWebService.UpdateResponse")
    public boolean update(
        @WebParam(name = "dataObject", targetNamespace = "http://xmlns.oracle.com/bam")
        String dataObject,
        @WebParam(name = "keysCSV", targetNamespace = "http://xmlns.oracle.com/bam")
        String keysCSV,
        @WebParam(name = "xmlPayload", targetNamespace = "http://xmlns.oracle.com/bam")
        String xmlPayload);

    /**
     * 
     * @param keysCSV
     * @param xmlPayload
     * @param dataObject
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Upsert", action = "http://xmlns.oracle.com/bam/Upsert")
    @WebResult(name = "UpsertResult", targetNamespace = "http://xmlns.oracle.com/bam")
    @RequestWrapper(localName = "Upsert", targetNamespace = "http://xmlns.oracle.com/bam", className = "ap.quantas.com.bamUpdateWebService.Upsert")
    @ResponseWrapper(localName = "UpsertResponse", targetNamespace = "http://xmlns.oracle.com/bam", className = "ap.quantas.com.bamUpdateWebService.UpsertResponse")
    public boolean upsert(
        @WebParam(name = "dataObject", targetNamespace = "http://xmlns.oracle.com/bam")
        String dataObject,
        @WebParam(name = "keysCSV", targetNamespace = "http://xmlns.oracle.com/bam")
        String keysCSV,
        @WebParam(name = "xmlPayload", targetNamespace = "http://xmlns.oracle.com/bam")
        String xmlPayload);

    /**
     * 
     * @param xmlPayload
     * @param dataObject
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Batch", action = "http://xmlns.oracle.com/bam/Batch")
    @WebResult(name = "BatchResult", targetNamespace = "http://xmlns.oracle.com/bam")
    @RequestWrapper(localName = "Batch", targetNamespace = "http://xmlns.oracle.com/bam", className = "ap.quantas.com.bamUpdateWebService.Batch")
    @ResponseWrapper(localName = "BatchResponse", targetNamespace = "http://xmlns.oracle.com/bam", className = "ap.quantas.com.bamUpdateWebService.BatchResponse")
    public boolean batch(
        @WebParam(name = "dataObject", targetNamespace = "http://xmlns.oracle.com/bam")
        String dataObject,
        @WebParam(name = "xmlPayload", targetNamespace = "http://xmlns.oracle.com/bam")
        String xmlPayload);

}
