package model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 08 14:35:46 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class POLineNumberDetailsVOImpl extends ViewObjectImpl {
  
   
  
    /**
     * This is the default constructor (do not remove).
     */
    public POLineNumberDetailsVOImpl() {
    }

    @Override
    public String getQuery() {
        System.out.println("Overrriding the POLineNumberDetailsQueryy!!!  "+ this.getQuery());
        
        
        return super.getQuery();
    }
}
