package model.views;

import java.math.BigDecimal;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 08 14:35:45 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class POLineNumberDetailsVORowImpl extends ViewRowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public POLineNumberDetailsVORowImpl() {
    }
}
