
package ap.quantas.com.js.eQApprovalService;



import ap.qantas.com.Utility;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
//dev--
//@WebServiceClient(name = "JSEQ_AP_INV_IMG_PROCESS_APPROVER_DTL-service", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/JetstarOsb/JetStarOsbApp/JSEQ_AP_INV_IMG_PROCESS_APPROVER_DTL", wsdlLocation = "http://eqdev-soa:16013/JetStarService/ProxyService/JETSTAR_APPROVER_DTL_PS?wsdl")
@WebServiceClient(name = "JSEQ_AP_INV_IMG_PROCESS_APPROVER_DTL-service", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/JetstarOsb/JetStarOsbApp/JSEQ_AP_INV_IMG_PROCESS_APPROVER_DTL", wsdlLocation = "http://eqosb.qantas.com.au/JetStarService/ProxyService/JETSTAR_APPROVER_DTL_PS?wsdl")
public class JSEQAPINVIMGPROCESSAPPROVERDTLService
    extends Service
{

    private final static URL JSEQAPINVIMGPROCESSAPPROVERDTLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ap.quantas.com.js.eQApprovalService.JSEQAPINVIMGPROCESSAPPROVERDTLService.class.getName());

    static {
        URL url = null;
         
        try {
            String approvalWorkflowUrl = Utility.resolveExpression("#{ApOperationBean.propertyLoader.properties['EBS_WORKFLOW_URL']}").toString();
            
            System.out.println("ebs approval workflow wsdl url :"+approvalWorkflowUrl);
            URL baseUrl;
            baseUrl = ap.quantas.com.js.eQApprovalService.JSEQAPINVIMGPROCESSAPPROVERDTLService.class.getResource(".");
//            url = new URL(baseUrl, "http://eqsit-db:16033/JetStarService/ProxyService/JETSTAR_APPROVER_DTL_PS?wsdl");
             url = new URL(baseUrl, approvalWorkflowUrl);
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location:  '"+Utility.resolveExpression("#{ApOperationBean.propertyLoader.properties['EBS_WORKFLOW_URL']}").toString() +"', retrying as a local file");
            logger.warning(e.getMessage());
        }
        catch (Exception e) {
                    System.out.println(e);
                }
        JSEQAPINVIMGPROCESSAPPROVERDTLSERVICE_WSDL_LOCATION = url;
    }

    public JSEQAPINVIMGPROCESSAPPROVERDTLService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JSEQAPINVIMGPROCESSAPPROVERDTLService() {
        super(JSEQAPINVIMGPROCESSAPPROVERDTLSERVICE_WSDL_LOCATION, new QName("http://xmlns.oracle.com/pcbpel/adapter/db/JetstarOsb/JetStarOsbApp/JSEQ_AP_INV_IMG_PROCESS_APPROVER_DTL", "JSEQ_AP_INV_IMG_PROCESS_APPROVER_DTL-service"));
    }

    /**
     * 
     * @return
     *     returns JSEQAPINVIMGPROCESSAPPROVERDTLPtt
     */
    @WebEndpoint(name = "JSEQ_AP_INV_IMG_PROCESS_APPROVER_DTL-port")
    public JSEQAPINVIMGPROCESSAPPROVERDTLPtt getJSEQAPINVIMGPROCESSAPPROVERDTLPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/pcbpel/adapter/db/JetstarOsb/JetStarOsbApp/JSEQ_AP_INV_IMG_PROCESS_APPROVER_DTL", "JSEQ_AP_INV_IMG_PROCESS_APPROVER_DTL-port"), JSEQAPINVIMGPROCESSAPPROVERDTLPtt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JSEQAPINVIMGPROCESSAPPROVERDTLPtt
     */
    @WebEndpoint(name = "JSEQ_AP_INV_IMG_PROCESS_APPROVER_DTL-port")
    public JSEQAPINVIMGPROCESSAPPROVERDTLPtt getJSEQAPINVIMGPROCESSAPPROVERDTLPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/pcbpel/adapter/db/JetstarOsb/JetStarOsbApp/JSEQ_AP_INV_IMG_PROCESS_APPROVER_DTL", "JSEQ_AP_INV_IMG_PROCESS_APPROVER_DTL-port"), JSEQAPINVIMGPROCESSAPPROVERDTLPtt.class, features);
    }

}
