
package ap.quantas.com.js.eQApprovalService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "JSEQ_AP_INV_IMG_PROCESS_APPROVER_DTL_ptt", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/JetstarOsb/JetStarOsbApp/JSEQ_AP_INV_IMG_PROCESS_APPROVER_DTL")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JSEQAPINVIMGPROCESSAPPROVERDTLPtt {


    /**
     * 
     * @param inputParameters
     * @return
     *     returns ap.quantas.com.js.eQApprovalService.OutputParameters
     */
    @WebMethod(operationName = "JSEQ_AP_INV_IMG_PROCESS_APPROVER_DTL", action = "JSEQ_AP_INV_IMG_PROCESS_APPROVER_DTL")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/JSEQ_AP_INV_IMG_PROCESS_APPROVER_DTL", partName = "OutputParameters")
    public OutputParameters jseqAPINVIMGPROCESSAPPROVERDTL(
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/JSEQ_AP_INV_IMG_PROCESS_APPROVER_DTL", partName = "InputParameters")
        InputParameters inputParameters);

}
