package qantas.com.au.overseas.model;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 24 17:59:39 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EBS_AMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EBS_AMImpl() {
    }

    /**
     * Container's getter for TaxRateCodeLookupVO1.
     * @return TaxRateCodeLookupVO1
     */
    public ViewObjectImpl getTaxRateCodeLookupVO1() {
        return (ViewObjectImpl)findViewObject("TaxRateCodeLookupVO1");
    }

    /**
     * Container's getter for SitesVO1.
     * @return SitesVO1
     */
    public ViewObjectImpl getSitesVO1() {
        return (ViewObjectImpl)findViewObject("SitesVO1");
    }

    /**
     * Container's getter for SitesDetailsVO1.
     * @return SitesDetailsVO1
     */
    public ViewObjectImpl getSitesDetailsVO1() {
        return (ViewObjectImpl)findViewObject("SitesDetailsVO1");
    }

    /**
     * Container's getter for POVO1.
     * @return POVO1
     */
    public ViewObjectImpl getPOVO1() {
        return (ViewObjectImpl)findViewObject("POVO1");
    }

    /**
     * Container's getter for CurrencyCodeVO1.
     * @return CurrencyCodeVO1
     */
    public ViewObjectImpl getCurrencyCodeVO1() {
        return (ViewObjectImpl)findViewObject("CurrencyCodeVO1");
    }

    /**
     * Container's getter for CertifierNameVO1.
     * @return CertifierNameVO1
     */
    public ViewObjectImpl getCertifierNameVO1() {
        return (ViewObjectImpl)findViewObject("CertifierNameVO1");
    }

    /**
     * Container's getter for CompanyCounterPartyVO1.
     * @return CompanyCounterPartyVO1
     */
    public ViewObjectImpl getCompanyCounterPartyVO1() {
        return (ViewObjectImpl)findViewObject("CompanyCounterPartyVO1");
    }

    /**
     * Container's getter for AnalysisCodeVO1.
     * @return AnalysisCodeVO1
     */
    public ViewObjectImpl getAnalysisCodeVO1() {
        return (ViewObjectImpl)findViewObject("AnalysisCodeVO1");
    }

    /**
     * Container's getter for AccountVO1.
     * @return AccountVO1
     */
    public ViewObjectImpl getAccountVO1() {
        return (ViewObjectImpl)findViewObject("AccountVO1");
    }

    /**
     * Container's getter for CostCentreVO1.
     * @return CostCentreVO1
     */
    public ViewObjectImpl getCostCentreVO1() {
        return (ViewObjectImpl)findViewObject("CostCentreVO1");
    }

    /**
     * Container's getter for ValidateGLCodeVO1.
     * @return ValidateGLCodeVO1
     */
    public ViewObjectImpl getValidateGLCodeVO1() {
        return (ViewObjectImpl)findViewObject("ValidateGLCodeVO1");
    }

    /**
     * Container's getter for ProjectNumberVO1.
     * @return ProjectNumberVO1
     */
    public ViewObjectImpl getProjectNumberVO1() {
        return (ViewObjectImpl)findViewObject("ProjectNumberVO1");
    }

    /**
     * Container's getter for TaskNumberVO1.
     * @return TaskNumberVO1
     */
    public ViewObjectImpl getTaskNumberVO1() {
        return (ViewObjectImpl)findViewObject("TaskNumberVO1");
    }

    /**
     * Container's getter for ExpenditureOrgVO1.
     * @return ExpenditureOrgVO1
     */
    public ViewObjectImpl getExpenditureOrgVO1() {
        return (ViewObjectImpl)findViewObject("ExpenditureOrgVO1");
    }

    /**
     * Container's getter for TaxRateCodeMasterListVO1.
     * @return TaxRateCodeMasterListVO1
     */
    public ViewObjectImpl getTaxRateCodeMasterListVO1() {
        return (ViewObjectImpl)findViewObject("TaxRateCodeMasterListVO1");
    }

    /**
     * Container's getter for PoNoCertifierVO1.
     * @return PoNoCertifierVO1
     */
    public ViewObjectImpl getPoNoCertifierVO1() {
        return (ViewObjectImpl)findViewObject("PoNoCertifierVO1");
    }

    /**
     * Container's getter for CertifierNameVO_ActiveOnlyRecords1.
     * @return CertifierNameVO_ActiveOnlyRecords1
     */
    public ViewObjectImpl getCertifierNameVO_ActiveOnlyRecords1() {
        return (ViewObjectImpl)findViewObject("CertifierNameVO_ActiveOnlyRecords1");
    }

    /**
     * Container's getter for gl_cc_overseas_suspense_check1.
     * @return gl_cc_overseas_suspense_check1
     */
    public ViewObjectImpl getgl_cc_overseas_suspense_check1() {
        return (ViewObjectImpl)findViewObject("gl_cc_overseas_suspense_check1");
    }

    /**
     * Container's getter for gl_cc_overseas_validation1.
     * @return gl_cc_overseas_validation1
     */
    public ViewObjectImpl getgl_cc_overseas_validation1() {
        return (ViewObjectImpl)findViewObject("gl_cc_overseas_validation1");
    }

    /**
     * Container's getter for TestViewObject1.
     * @return TestViewObject1
     */
    public ViewObjectImpl getTestViewObject1() {
        return (ViewObjectImpl)findViewObject("TestViewObject1");
    }

    /**
     * Container's getter for POLineDetailsVO1.
     * @return POLineDetailsVO1
     */
    public ViewObjectImpl getPOLineDetailsVO1() {
        return (ViewObjectImpl)findViewObject("POLineDetailsVO1");
    }

    /**
     * Container's getter for POLineNumberDetailsVO1.
     * @return POLineNumberDetailsVO1
     */
    public ViewObjectImpl getPOLineNumberDetailsVO1() {
        return (ViewObjectImpl)findViewObject("POLineNumberDetailsVO1");
    }

    /**
     * Container's getter for ExpenditureDateVO1.
     * @return ExpenditureDateVO1
     */
    public ViewObjectImpl getExpenditureDateVO1() {
        return (ViewObjectImpl)findViewObject("ExpenditureDateVO1");
    }

    /**
     * Container's getter for ExpenditureTypeVO1.
     * @return ExpenditureTypeVO1
     */
    public ViewObjectImpl getExpenditureTypeVO1() {
        return (ViewObjectImpl)findViewObject("ExpenditureTypeVO1");
    }

    /**
     * Container's getter for ValidateRoundingAmount1.
     * @return ValidateRoundingAmount1
     */
    public ViewObjectImpl getValidateRoundingAmount1() {
        return (ViewObjectImpl) findViewObject("ValidateRoundingAmount1");
    }

    /**
     * Container's getter for ValidateTaxCalcRounding1.
     * @return ValidateTaxCalcRounding1
     */
    public ViewObjectImpl getValidateTaxCalcRounding1() {
        return (ViewObjectImpl) findViewObject("ValidateTaxCalcRounding1");
    }
}
