
package eq.integration.file;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "QFEQIFFileLockingService", targetNamespace = "http://file.integration.eq/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QFEQIFFileLockingService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLock", targetNamespace = "http://file.integration.eq/", className = "eq.integration.file.GetLock")
    @ResponseWrapper(localName = "getLockResponse", targetNamespace = "http://file.integration.eq/", className = "eq.integration.file.GetLockResponse")
    @Action(input = "http://file.integration.eq/QFEQIFFileLockingService/getLockRequest", output = "http://file.integration.eq/QFEQIFFileLockingService/getLockResponse")
    public boolean getLock(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "releaseLock", targetNamespace = "http://file.integration.eq/", className = "eq.integration.file.ReleaseLock")
    @ResponseWrapper(localName = "releaseLockResponse", targetNamespace = "http://file.integration.eq/", className = "eq.integration.file.ReleaseLockResponse")
    @Action(input = "http://file.integration.eq/QFEQIFFileLockingService/releaseLockRequest", output = "http://file.integration.eq/QFEQIFFileLockingService/releaseLockResponse")
    public void releaseLock(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
