
package eq.integration.file;

import java.io.FileInputStream;
import java.net.URL;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
//dev--@WebServiceClient(name = "QFEQIFFileLockingServiceService", targetNamespace = "http://file.integration.eq/", wsdlLocation = "http://eqdev-soa.qantas.com.au:16015/IHubFileMgmt/QFEQIFFileLockingServicePort?WSDL")-DEV
//sit direct--@WebServiceClient(name = "QFEQIFFileLockingServiceService", targetNamespace = "http://file.integration.eq/", wsdlLocation = "http://172.27.45.4:18036/IHubFileMgmt/QFEQIFFileLockingServicePort?WSDL")//SIT
//soa loab balancer--@WebServiceClient(name = "QFEQIFFileLockingServiceService", targetNamespace = "http://file.integration.eq/", wsdlLocation = "http://eqsoasit.qantas.com.au/IHubFileMgmt/QFEQIFFileLockingServicePort?WSDL")//SIT
//@WebServiceClient(name = "QFEQIFFileLockingServiceService", targetNamespace = "http://file.integration.eq/", wsdlLocation = "http://eqjeesit.qantas.com.au/IHubFileMgmt/QFEQIFFileLockingServicePort?WSDL")//SIT
//psp - @WebServiceClient(name = "QFEQIFFileLockingServiceService", targetNamespace = "http://file.integration.eq/", wsdlLocation = "http://eqsoapspnew.qantas.com.au/IHubFileMgmt/QFEQIFFileLockingServicePort?WSDL")//SIT

@WebServiceClient(name = "QFEQIFFileLockingServiceService", targetNamespace = "http://file.integration.eq/", wsdlLocation = "http://eqjee.qantas.com.au/IHubFileMgmt/QFEQIFFileLockingServicePort?WSDL")//SIT
public class QFEQIFFileLockingServiceService
    extends Service
{

    private final static URL QFEQIFFILELOCKINGSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException QFEQIFFILELOCKINGSERVICESERVICE_EXCEPTION;
    private final static QName QFEQIFFILELOCKINGSERVICESERVICE_QNAME = new QName("http://file.integration.eq/", "QFEQIFFileLockingServiceService");
    private static Logger logger;
    static {
    	
    	//
    	URL url = null;
    	WebServiceException e = null;
        try
        {
            String configFile = System.getenv("QFEQIF_CONFIG");
            Properties pro = new Properties();
            pro.load(new FileInputStream(configFile));
            
          logger = Logger.getLogger("com.qantas.eq.OutboundService.client.QFEQ_Outbound_WF015Service");
       
          url = new URL(pro.getProperty("FILE_LOCKING_URL"));
          
        }
        catch (Exception ex)
        {
          logger.log(Level.ALL,
              "Failed to create wsdlLocationURL using http://172.27.45.4:16035/IHubFileMgmt/QFEQIFFileLockingServicePort?WSDL",
              ex);
          e=new WebServiceException(ex);
        }
      
    	
    	
    	
    	
    	///
    	
    	
    	
    	
    	
    	
      /*  URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://eqdev-soa.qantas.com.au:16015/IHubFileMgmt/QFEQIFFileLockingServicePort?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }*/
        QFEQIFFILELOCKINGSERVICESERVICE_WSDL_LOCATION = url;
        QFEQIFFILELOCKINGSERVICESERVICE_EXCEPTION = e;
    }

    public QFEQIFFileLockingServiceService() {
        super(__getWsdlLocation(), QFEQIFFILELOCKINGSERVICESERVICE_QNAME);
    }

    public QFEQIFFileLockingServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), QFEQIFFILELOCKINGSERVICESERVICE_QNAME, features);
    }

    public QFEQIFFileLockingServiceService(URL wsdlLocation) {
        super(wsdlLocation, QFEQIFFILELOCKINGSERVICESERVICE_QNAME);
    }

    public QFEQIFFileLockingServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QFEQIFFILELOCKINGSERVICESERVICE_QNAME, features);
    }

    public QFEQIFFileLockingServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QFEQIFFileLockingServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns QFEQIFFileLockingService
     */
    @WebEndpoint(name = "QFEQIFFileLockingServicePort")
    public QFEQIFFileLockingService getQFEQIFFileLockingServicePort() {
        return super.getPort(new QName("http://file.integration.eq/", "QFEQIFFileLockingServicePort"), QFEQIFFileLockingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QFEQIFFileLockingService
     */
    @WebEndpoint(name = "QFEQIFFileLockingServicePort")
    public QFEQIFFileLockingService getQFEQIFFileLockingServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://file.integration.eq/", "QFEQIFFileLockingServicePort"), QFEQIFFileLockingService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QFEQIFFILELOCKINGSERVICESERVICE_EXCEPTION!= null) {
            throw QFEQIFFILELOCKINGSERVICESERVICE_EXCEPTION;
        }
        return QFEQIFFILELOCKINGSERVICESERVICE_WSDL_LOCATION;
    }

}
