package ap.qantas.com.eQApprovalDetailsService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://eqosb.qantas.com.au/ApproverService/ApproverPS?wsdl",
  targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TesteQRule/BusinessRulePrj/approverDetails",
  name="approverDetails_ptt")
@XmlSeeAlso(
  { ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface ApproverDetails_ptt
{
  @WebMethod(action="approverDetails")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="approverDetails", output="http://xmlns.oracle.com/pcbpel/adapter/db/TesteQRule/BusinessRulePrj/approverDetails/approverDetails_ptt/approverDetailsResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/approverDetails",
    partName="OutputParameters", name="OutputParameters")
  public OutputParameters approverDetails(@WebParam(targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/approverDetails",
      partName="InputParameters", name="InputParameters")
    InputParameters InputParameters);
}
