package ap.qantas.com.eQApprovalDetailsService;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.el.ELContext;
import javax.el.ExpressionFactory;

import javax.el.ValueExpression;

import javax.faces.application.Application;
import javax.faces.context.FacesContext;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="http://eqosb.qantas.com.au/ApproverService/ApproverPS?wsdl",
  targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TesteQRule/BusinessRulePrj/approverDetails",
  name="approverDetails_ptt-bindingQSService")
public class ApproverDetails_pttBindingQSService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;

    public static FacesContext getFacesContext() {
        return FacesContext.getCurrentInstance();
    }

    public static Object resolveExpression(String expression) {
        FacesContext facesContext = getFacesContext();
        Application app = facesContext.getApplication();
        ExpressionFactory elFactory = app.getExpressionFactory();
        ELContext elContext = facesContext.getELContext();
        ValueExpression valueExp =
            elFactory.createValueExpression(elContext, expression,
                                            Object.class);
        return valueExp.getValue(elContext);
    }

  static
  {
    try
    {
        //System.out.println("Wsdl :" +resolveExpression("#{ApOperationBean.propertyLoader.properties['EBS_APPROVER_SERVICE_WSDL']}").toString());
      logger = Logger.getLogger("ap.qantas.com.eQApprovalDetailsService.ApproverDetails_pttBindingQSService");
      URL baseUrl =
        ApproverDetails_pttBindingQSService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            ApproverDetails_pttBindingQSService.class.getResource(resolveExpression("#{backing_ap_overseasPage.propertyLoader.properties['EBS_APPROVER_SERVICE_WSDL']}").toString());
           //ApproverDetails_pttBindingQSService.class.getResource(resolveExpression("#{ApOperationBean.propertyLoader.properties['EBS_APPROVER_SERVICE_WSDL']}").toString());
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, resolveExpression("#{backing_ap_overseasPage.propertyLoader.properties['EBS_APPROVER_SERVICE_WSDL']}").toString());
             // new URL(baseUrl, resolveExpression("#{ApOperationBean.propertyLoader.properties['EBS_APPROVER_SERVICE_WSDL']}").toString());
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
          // new URL(baseUrl, "http://eqdr-soa-ap1:16034/ApproverService/ApproverPS?wsdl");
          new URL(baseUrl, resolveExpression("#{backing_ap_overseasPage.propertyLoader.properties['EBS_APPROVER_SERVICE_WSDL']}").toString());
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
         // "Failed to create wsdlLocationURL using http://eqdr-soa-ap1:16034/ApproverService/ApproverPS?wsdl",
       "Failed to create wsdlLocationURL using "+resolveExpression("#{backing_ap_overseasPage.propertyLoader.properties['EBS_APPROVER_SERVICE_WSDL']}").toString(),
          e);
    }
    catch(Exception e1){
        System.out.println(e1);
        e1.printStackTrace();
    }
  }

  public ApproverDetails_pttBindingQSService()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/pcbpel/adapter/db/TesteQRule/BusinessRulePrj/approverDetails",
                    "approverDetails_ptt-bindingQSService"));
  }

  public ApproverDetails_pttBindingQSService(URL wsdlLocation,
                                             QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="approverDetails_ptt-bindingQSPort")
  public ApproverDetails_ptt getApproverDetails_pttBindingQSPort()
  {
    return (ApproverDetails_ptt) super.getPort(new QName("http://xmlns.oracle.com/pcbpel/adapter/db/TesteQRule/BusinessRulePrj/approverDetails",
                                                         "approverDetails_ptt-bindingQSPort"),
                                               ApproverDetails_ptt.class);
  }

  @WebEndpoint(name="approverDetails_ptt-bindingQSPort")
  public ApproverDetails_ptt getApproverDetails_pttBindingQSPort(WebServiceFeature... features)
  {
    return (ApproverDetails_ptt) super.getPort(new QName("http://xmlns.oracle.com/pcbpel/adapter/db/TesteQRule/BusinessRulePrj/approverDetails",
                                                         "approverDetails_ptt-bindingQSPort"),
                                               ApproverDetails_ptt.class,
                                               features);
  }
}
