
package ap.quantas.com.ebsAutofillWebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Update_ptt", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/Application3/soa/Update")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UpdatePtt {


    /**
     * 
     * @param inputParameters
     * @return
     *     returns ap.quantas.com.ebs_webservice.OutputParameters
     */
    @WebMethod(operationName = "Update", action = "Update")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/Update", partName = "OutputParameters")
    public OutputParameters update(
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/Update", partName = "InputParameters")
        InputParameters inputParameters);

}
