package ap.quantas.com.holdReleaseWebService;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.el.ELContext;
import javax.el.ExpressionFactory;
import javax.el.ValueExpression;

import javax.faces.application.Application;
import javax.faces.context.FacesContext;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

//dev--
//@WebServiceClient(wsdlLocation="http://eqdev-soa:16015/integration/services/TaskService/TaskServicePort?WSDL",
@WebServiceClient(wsdlLocation="http://eqsoa.qantas.com.au/integration/services/TaskService/TaskServicePort?WSDL",
  targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
  name="TaskService")
public class TaskService_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  
    public static FacesContext getFacesContext() {
        return FacesContext.getCurrentInstance();
    }

    public static Object resolveExpression(String expression) {
        FacesContext facesContext = getFacesContext();
        Application app = facesContext.getApplication();
        ExpressionFactory elFactory = app.getExpressionFactory();
        ELContext elContext = facesContext.getELContext();
        ValueExpression valueExp =
            elFactory.createValueExpression(elContext, expression,
                                            Object.class);
        return valueExp.getValue(elContext);
    }
    
  static
  {
      URL url = null;
    try
        {
      String holdrelease=
          resolveExpression("#{ApOperationBean.propertyLoader.properties['BPM_HOLDRELEASE_SERVICE_WSDL']}").toString();
         // "http://eqdr-soa-ap1:16035/integration/services/TaskService/TaskServicePort?WSDL";
      
      System.out.println("holdrelease wsdl url :: "+holdrelease);
      
   
      logger = Logger.getLogger("ap.quantas.com.holdReleaseWebService.TaskService_Service");
      
      URL baseUrl = TaskService_Service.class.getResource(".");
        System.out.println("1");
        url = new URL(baseUrl, holdrelease);
        System.out.println("2");
      if (baseUrl == null)
      {
          System.out.println("3");
        wsdlLocationURL =url;
           // TaskService_Service.class.getResource("http://eqsit-ap:16035/integration/services/TaskService/TaskServicePort?WSDL");
           System.out.println("4");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =url;
            //  new URL(baseUrl, "http://eqsit-ap:16035/integration/services/TaskService/TaskServicePort?WSDL");
            System.out.println("5");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =url;
          System.out.println("6");
           // new URL(baseUrl, "http://eqsit-ap:16035/integration/services/TaskService/TaskServicePort?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
     /* logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://eqsit-ap:16035/integration/services/TaskService/TaskServicePort?WSDL",
          e);*/
     System.out.println("7");
     logger.log(Level.ALL,
         "Failed to create wsdlLocationURL using "+url,
         e);
    }
      catch (Exception e)
      {
       /* logger.log(Level.ALL,
            "Failed to create wsdlLocationURL using http://eqsit-ap:16035/integration/services/TaskService/TaskServicePort?WSDL",
            e);*/
       System.out.println(e);
       
      }
  }

  public TaskService_Service()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/bpel/workflow/taskService",
                    "TaskService"));
  }

  public TaskService_Service(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="TaskServicePort")
  public ap.quantas.com.holdReleaseWebService.TaskService getTaskServicePort()
  {
    return (ap.quantas.com.holdReleaseWebService.TaskService) super.getPort(new QName("http://xmlns.oracle.com/bpel/workflow/taskService",
                                                                              "TaskServicePort"),
                                                                    ap.quantas.com.holdReleaseWebService.TaskService.class);
  }

  @WebEndpoint(name="TaskServicePort")
  public ap.quantas.com.holdReleaseWebService.TaskService getTaskServicePort(WebServiceFeature... features)
  {
    return (ap.quantas.com.holdReleaseWebService.TaskService) super.getPort(new QName("http://xmlns.oracle.com/bpel/workflow/taskService",
                                                                              "TaskServicePort"),
                                                                    ap.quantas.com.holdReleaseWebService.TaskService.class,
                                                                    features);
  }

  @WebEndpoint(name="TaskServicePortSAML")
  public ap.quantas.com.holdReleaseWebService.TaskService getTaskServicePortSAML()
  {
    return (ap.quantas.com.holdReleaseWebService.TaskService) super.getPort(new QName("http://xmlns.oracle.com/bpel/workflow/taskService",
                                                                              "TaskServicePortSAML"),
                                                                    ap.quantas.com.holdReleaseWebService.TaskService.class);
  }

  @WebEndpoint(name="TaskServicePortSAML")
  public ap.quantas.com.holdReleaseWebService.TaskService getTaskServicePortSAML(WebServiceFeature... features)
  {
    return (ap.quantas.com.holdReleaseWebService.TaskService) super.getPort(new QName("http://xmlns.oracle.com/bpel/workflow/taskService",
                                                                              "TaskServicePortSAML"),
                                                                    ap.quantas.com.holdReleaseWebService.TaskService.class,
                                                                    features);
  }
}
