package ap.quantas.com.holdReleaseWebService;

import ap.quantas.com.holdReleaseWebService.TaskService_Service;
import ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskServiceContextTaskTaskIdBaseType;
import javax.xml.ws.WebServiceRef;

import ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.common.model.CredentialType;
import ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.common.model.WorkflowContextType;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

public class TaskServicePortClient
{
  @WebServiceRef
  private static TaskService_Service taskService_Service;

  public static void main(String [] args)
  {
    //taskService_Service = new TaskService_Service();
   // TaskService taskService = taskService_Service.getTaskServicePort();
    // Add your code to call the desired methods.
    
    try {
        TaskService_Service service = new TaskService_Service();

        TaskServiceContextTaskTaskIdBaseType taskServiceContextTaskTaskIdBaseType =
            new TaskServiceContextTaskTaskIdBaseType();

        taskServiceContextTaskTaskIdBaseType.setTaskId("633109e6-d625-4324-850e-8d44345f01bc");
        

        WorkflowContextType workflowContextType =
            new WorkflowContextType();

        CredentialType credentialType = new CredentialType();
        credentialType.setLogin("eqadmin");
        credentialType.setPassword("eQs0a@dmin123");
        workflowContextType.setCredential(credentialType);


        taskServiceContextTaskTaskIdBaseType.setWorkflowContext(workflowContextType);

        //service.getTaskServicePort().suspendTimers(taskServiceContextTaskTaskIdBaseType);
       
        
        service.getTaskServicePort().resumeTimers(taskServiceContextTaskTaskIdBaseType);
        System.out.println("Done");
    } catch (StaleObjectFaultMessage sofm) {
        // TODO: Add catch code
        sofm.printStackTrace();
    } catch (WorkflowErrorMessage wem) {
        // TODO: Add catch code
        wem.printStackTrace();
    }
  }
}
