package ap.quantas.com.jsEbsCalculateDueDate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

//dev--
//@WebService(wsdlLocation="http://eqdev-soa:16013/JetStarService/ProxyService/JETSTAR_AUTO_POPULATE?wsdl",
@WebService(wsdlLocation="http://eqosb.qantas.com.au/JetStarService/ProxyService/JETSTAR_AUTO_POPULATE?wsdl",
  targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/JetstarOsb/JetStarOsbApp/JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE",
  name="JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE_ptt")
@XmlSeeAlso(
  { ap.quantas.com.jsEbsCalculateDueDate.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE_ptt
{
  @WebMethod(operationName="JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE",
    action="JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE", output="http://xmlns.oracle.com/pcbpel/adapter/db/JetstarOsb/JetStarOsbApp/JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE/JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE_ptt/JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATEResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE",
    partName="OutputParameters", name="OutputParameters")
  public ap.quantas.com.jsEbsCalculateDueDate.OutputParameters jseqAPINVIMGPROCESSAUTOPOPULATE(@WebParam(targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE",
      partName="InputParameters", name="InputParameters")
    ap.quantas.com.jsEbsCalculateDueDate.InputParameters InputParameters);
}
