package ap.quantas.com.jsEbsCalculateDueDate;

import ap.qantas.com.Utility;

import ap.qantas.com.ebsCalculateWHTAmountService.JSEQ_AP_INV_IMG_PROCESS_CAL_AMTService;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)
//dev--
//@WebServiceClient(wsdlLocation="http://eqdev-soa:16013/JetStarService/ProxyService/JETSTAR_AUTO_POPULATE?wsdl",
@WebServiceClient(wsdlLocation="http://eqosb.qantas.com.au/JetStarService/ProxyService/JETSTAR_AUTO_POPULATE?wsdl",
  targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/JetstarOsb/JetStarOsbApp/JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE",
  name="JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE-service")
public class JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATEService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
      URL url = null;
      
      
    try
    {
        URL baseUrl;
        String approvalWorkflowUrl = Utility.resolveExpression("#{ApOperationBean.propertyLoader.properties['EBS_JS_AUTO_POPULATE_PS']}").toString();
        
        baseUrl = JSEQ_AP_INV_IMG_PROCESS_CAL_AMTService.class.getResource(".");
        //            url = new URL(baseUrl, "http://eqsit-db:16033/JetStarService/ProxyService/JETSTAR_APPROVER_DTL_PS?wsdl");
         url = new URL(baseUrl, approvalWorkflowUrl);
        
        
        
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://eqosb.qantas.com.au/JetStarService/ProxyService/JETSTAR_AUTO_POPULATE?wsdl",
          e);
    }
      catch (Exception e)
      {
          System.out.println(e);
      }
    
      wsdlLocationURL = url;
  }

  public JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATEService()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/pcbpel/adapter/db/JetstarOsb/JetStarOsbApp/JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE",
                    "JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE-service"));
  }

  public JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATEService(URL wsdlLocation,
                                                      QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE-port")
  public ap.quantas.com.jsEbsCalculateDueDate.JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE_ptt getJSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATEPort()
  {
    return (ap.quantas.com.jsEbsCalculateDueDate.JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE_ptt) super.getPort(new QName("http://xmlns.oracle.com/pcbpel/adapter/db/JetstarOsb/JetStarOsbApp/JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE",
                                                                                                                    "JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE-port"),
                                                                                                          ap.quantas.com.jsEbsCalculateDueDate.JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE_ptt.class);
  }

  @WebEndpoint(name="JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE-port")
  public ap.quantas.com.jsEbsCalculateDueDate.JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE_ptt getJSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATEPort(WebServiceFeature... features)
  {
    return (ap.quantas.com.jsEbsCalculateDueDate.JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE_ptt) super.getPort(new QName("http://xmlns.oracle.com/pcbpel/adapter/db/JetstarOsb/JetStarOsbApp/JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE",
                                                                                                                    "JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE-port"),
                                                                                                          ap.quantas.com.jsEbsCalculateDueDate.JSEQ_AP_INV_IMG_PROCESS_AUTO_POPULATE_ptt.class,
                                                                                                          features);
  }
}
