package ap.qantas.com.ebsCalculateWHTAmountService;

import ap.quantas.com.Utility;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)
//dev--
//@WebServiceClient(wsdlLocation="http://eqdev-soa:16013/JetStarService/ProxyService/JESTAR_CAL_AMT_PS?wsdl",
@WebServiceClient(wsdlLocation="http://eqosb.qantas.com.au/JetStarService/ProxyService/JESTAR_CAL_AMT_PS?wsdl",
  targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/JetstarOsb/JetStarOsbApp/JSEQ_AP_INV_IMG_PROCESS_CAL_AMT",
  name="JSEQ_AP_INV_IMG_PROCESS_CAL_AMT-service")
public class JSEQ_AP_INV_IMG_PROCESS_CAL_AMTService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
        
        //Utility.resolveExpression("#{ApOperationBean.propertyLoader.properties['GET_INVOICE_DUE_DATE_SERVICE_WSDL']}").toString();
      logger = Logger.getLogger("test.JSEQ_AP_INV_IMG_PROCESS_CAL_AMTService");
      URL baseUrl =
        JSEQ_AP_INV_IMG_PROCESS_CAL_AMTService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
          JSEQ_AP_INV_IMG_PROCESS_CAL_AMTService.class.getResource("http://eqosb.qantas.com.au/JetStarService/ProxyService/JESTAR_CAL_AMT_PS?wsdl");
         //JSEQ_AP_INV_IMG_PROCESS_CAL_AMTService.class.getResource("http://eqosbnew.qantas.com.au/JetStarService/ProxyService/JESTAR_CAL_AMT_PS?wsdl");
//         JSEQ_AP_INV_IMG_PROCESS_CAL_AMTService.class.getResource("http://eqdev-soa:16013/JetStarService/ProxyService/JESTAR_CAL_AMT_PS?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
            new URL(baseUrl, "http://eqosb.qantas.com.au/JetStarService/ProxyService/JESTAR_CAL_AMT_PS?wsdl");
            //new URL(baseUrl, "http://eqosbnew.qantas.com.au/JetStarService/ProxyService/JESTAR_CAL_AMT_PS?wsdl");
//            new URL(baseUrl, "http://eqdev-soa:16013/JetStarService/ProxyService/JESTAR_CAL_AMT_PS?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
          new URL(baseUrl, "http://eqosb.qantas.com.au/JetStarService/ProxyService/JESTAR_CAL_AMT_PS?wsdl");
         //new URL(baseUrl, "http://eqosbnew.qantas.com.au/JetStarService/ProxyService/JESTAR_CAL_AMT_PS?wsdl");
//         new URL(baseUrl, "http://eqdev-soa:16013/JetStarService/ProxyService/JESTAR_CAL_AMT_PS?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://eqosb.qantas.com.au/JetStarService/ProxyService/JESTAR_CAL_AMT_PS?wsdl",
          e);
    }
      catch (Exception e)
      {
          System.out.println(e);
      }
  }

  public JSEQ_AP_INV_IMG_PROCESS_CAL_AMTService()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/pcbpel/adapter/db/JetstarOsb/JetStarOsbApp/JSEQ_AP_INV_IMG_PROCESS_CAL_AMT",
                    "JSEQ_AP_INV_IMG_PROCESS_CAL_AMT-service"));
  }

  public JSEQ_AP_INV_IMG_PROCESS_CAL_AMTService(URL wsdlLocation,
                                                QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="JSEQ_AP_INV_IMG_PROCESS_CAL_AMT-port")
  public ap.qantas.com.ebsCalculateWHTAmountService.JSEQ_AP_INV_IMG_PROCESS_CAL_AMT_ptt getJSEQ_AP_INV_IMG_PROCESS_CAL_AMTPort()
  {
    return (ap.qantas.com.ebsCalculateWHTAmountService.JSEQ_AP_INV_IMG_PROCESS_CAL_AMT_ptt) super.getPort(new QName("http://xmlns.oracle.com/pcbpel/adapter/db/JetstarOsb/JetStarOsbApp/JSEQ_AP_INV_IMG_PROCESS_CAL_AMT",
                                                                              "JSEQ_AP_INV_IMG_PROCESS_CAL_AMT-port"),
                                                                    ap.qantas.com.ebsCalculateWHTAmountService.JSEQ_AP_INV_IMG_PROCESS_CAL_AMT_ptt.class);
  }

  @WebEndpoint(name="JSEQ_AP_INV_IMG_PROCESS_CAL_AMT-port")
  public ap.qantas.com.ebsCalculateWHTAmountService.JSEQ_AP_INV_IMG_PROCESS_CAL_AMT_ptt getJSEQ_AP_INV_IMG_PROCESS_CAL_AMTPort(WebServiceFeature... features)
  {
    return (ap.qantas.com.ebsCalculateWHTAmountService.JSEQ_AP_INV_IMG_PROCESS_CAL_AMT_ptt) super.getPort(new QName("http://xmlns.oracle.com/pcbpel/adapter/db/JetstarOsb/JetStarOsbApp/JSEQ_AP_INV_IMG_PROCESS_CAL_AMT",
                                                                              "JSEQ_AP_INV_IMG_PROCESS_CAL_AMT-port"),
                                                                    ap.qantas.com.ebsCalculateWHTAmountService.JSEQ_AP_INV_IMG_PROCESS_CAL_AMT_ptt.class,
                                                                    features);
  }
}
