package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 18 16:10:07 IST 2016
// ---------------------------------------------------------------------
public interface APOperationAM extends ApplicationModule {


    void addLineItemRow(String invoiceId);

    void saveAPOperationDetails(Boolean flag, String invoiceId, String supName,
                                String siteId, String invNum, String taxRegNum,
                                String poNum, String lineTotal,
                                String certName, String currency,
                                String invDate, String taxTotal,
                                String headerTotal, String certEmail,
                                String rejReason, String comments,
                                String certComments, String reason,
                                String type, String status, String docType,
                                String invoiceType, String operatingUnit,
                                String invalidReasonType, String invalidReason,
                                String employeeNo);

    void removeLineItemRow(String invoiceId);

    void addCommentsTableRow(String invoiceID, String commentsDate,
                             String category, String description, String name);

    void calculateWHTAmount(String SupplierSiteNumber, String invoiceDate,
                            String currencyCodes, String orgID);

    void executeHeaderLineItemDetails(String invoiceId, String pageName);
}
