package model.client;

import model.common.CertifierNameVO_ActiveOnlyRecords;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 11 14:04:19 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CertifierNameVO_ActiveOnlyRecordsClient extends ViewUsageImpl implements CertifierNameVO_ActiveOnlyRecords {
    /**
     * This is the default constructor (do not remove).
     */
    public CertifierNameVO_ActiveOnlyRecordsClient() {
    }


    public void filterCertifierByOU_Names(String bindName, String bvEmployeeID,
                                          String bindEmailAddress,
                                          String ou_namesSeperatedByComma,
                                          String viewCriteriaName,
                                          String methodName,
                                          String currentEmployeeId) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"filterCertifierByOU_Names",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {bindName, bvEmployeeID, bindEmailAddress, ou_namesSeperatedByComma, viewCriteriaName, methodName, currentEmployeeId});
        return;
    }

    public void filterCertifierByOU_Names(String bindName, String bvEmployeeID,
                                          String bindEmailAddress,
                                          String ou_namesSeperatedByComma,
                                          String viewCriteriaName,
                                          String methodName) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"filterCertifierByOU_Names",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {bindName, bvEmployeeID, bindEmailAddress, ou_namesSeperatedByComma, viewCriteriaName, methodName});
        return;
    }
}
