package qantas.com.router;

import javax.xml.ws.WebServiceRef;

import org.invoicerouter.InvoiceImport;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

public class RouterProcess_ptClient
{
  @WebServiceRef
  private static RouterProcess_EP_ep routerProcess_EP_ep;

  public static void main(String [] args)
  {
    routerProcess_EP_ep = new RouterProcess_EP_ep();
    RouterProcess routerProcess = routerProcess_EP_ep.getRouterProcess_pt();
      InvoiceImport payload = new InvoiceImport();
      InvoiceImport.Header obj=new InvoiceImport.Header();  
    
      
      routerProcess.process(payload);
      System.out.println("routerProcess called successfully");
    // Add your code to call the desired methods.
  }
}
