package qantas.com.router;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="http://eqsoa.qantas.com.au/soa-infra/services/default/Qantas_JSRouter/RouterProcess_EP_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/JetStarApplication/Qantas_JSRouter/RouterProcess",
  name="RouterProcess_EP_ep")
public class RouterProcess_EP_ep
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("qantas.com.router.RouterProcess_EP_ep");
      URL baseUrl = RouterProcess_EP_ep.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            RouterProcess_EP_ep.class.getResource("http://eqsoa.qantas.com.au/soa-infra/services/default/Qantas_JSRouter/RouterProcess_EP_ep?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://eqsoa.qantas.com.au/soa-infra/services/default/Qantas_JSRouter/RouterProcess_EP_ep?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://eqsoa.qantas.com.au/soa-infra/services/default/Qantas_JSRouter/RouterProcess_EP_ep?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://eqsoa.qantas.com.au/soa-infra/services/default/Qantas_JSRouter/RouterProcess_EP_ep?WSDL",
          e);
    }
    catch(Exception e1){
        System.out.println(e1);
        e1.printStackTrace();
    }
  }

  public RouterProcess_EP_ep()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/JetStarApplication/Qantas_JSRouter/RouterProcess",
                    "RouterProcess_EP_ep"));
  }

  public RouterProcess_EP_ep(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="RouterProcess_pt")
  public qantas.com.router.RouterProcess getRouterProcess_pt()
  {
    return (qantas.com.router.RouterProcess) super.getPort(new QName("http://xmlns.oracle.com/JetStarApplication/Qantas_JSRouter/RouterProcess",
                                                                     "RouterProcess_pt"),
                                                           qantas.com.router.RouterProcess.class);
  }

  @WebEndpoint(name="RouterProcess_pt")
  public qantas.com.router.RouterProcess getRouterProcess_pt(WebServiceFeature... features)
  {
    return (qantas.com.router.RouterProcess) super.getPort(new QName("http://xmlns.oracle.com/JetStarApplication/Qantas_JSRouter/RouterProcess",
                                                                     "RouterProcess_pt"),
                                                           qantas.com.router.RouterProcess.class,
                                                           features);
  }
}
