package qantas.com.router;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://eqsoa.qantas.com.au/soa-infra/services/default/Qantas_JSRouter/RouterProcess_EP_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/JetStarApplication/Qantas_JSRouter/RouterProcess",
  name="RouterProcess")
@XmlSeeAlso(
  { org.invoicerouter.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface RouterProcess
{
  @WebMethod(action="process")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="process")
  @Oneway
  public void process(@WebParam(targetNamespace="http://www.InvoiceRouter.org",
      partName="payload", name="invoiceImport")
    org.invoicerouter.InvoiceImport payload);
}
