<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns0="http://www.FetchUpdateParam.org" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns1="http://www.InvoiceData.org" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns0 xsd ns1 bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../xsd/FetchUpdateParam.xsd"/>
            <oracle-xsl-mapper:rootElement name="FetchUpdateData" namespace="http://www.FetchUpdateParam.org"/>
            <oracle-xsl-mapper:param name="FlexUpdatePDO"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../xsd/InvoiceData.xsd"/>
            <oracle-xsl-mapper:rootElement name="invoiceImport" namespace="http://www.InvoiceData.org"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [FRI SEP 09 21:33:38 AEST 2022].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns1:invoiceImport>
      <ns1:header>
        <ns1:documentType>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:DOCUMENT_TYPE"/>
        </ns1:documentType>
        <ns1:invoiceType>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:INVOICE_TYPE"/>
        </ns1:invoiceType>
        <ns1:orgID>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:ORG_ID"/>
        </ns1:orgID>
        <ns1:invoiceNumber>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:INVOICE_NUMBER"/>
        </ns1:invoiceNumber>
        <ns1:invoiceDate>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:INVOICE_DATE"/>
        </ns1:invoiceDate>
        <ns1:supplierId>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:SUPPLIER_ID"/>
        </ns1:supplierId>
        <ns1:supplierName>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:SUPPLIER_NAME"/>
        </ns1:supplierName>
        <ns1:supplierNumber>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:SUPPLIER_NUMBER"/>
        </ns1:supplierNumber>
        <ns1:SiteID>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:SITE_ID"/>
        </ns1:SiteID>
        <ns1:SiteName>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:SITE_NAME"/>
        </ns1:SiteName>
        <ns1:PONumber>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:PO_NUMBER"/>
        </ns1:PONumber>
        <ns1:tax>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:TAX_AMOUNT"/>
        </ns1:tax>
        <ns1:withholdingTax>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:WITHHOLDING_TAX"/>
        </ns1:withholdingTax>
        <ns1:invoiceTotalAmount>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:INVOICE_TOT_AMOUNT"/>
        </ns1:invoiceTotalAmount>
        <ns1:currencyCode>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:CURRENCY_CODE"/>
        </ns1:currencyCode>
        <ns1:certifierName>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:CERTIFIER_NAME"/>
        </ns1:certifierName>
        <ns1:employeeno>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:EMPLOYEE_NUMBER"/>
        </ns1:employeeno>
        <ns1:certifieremailAdd>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:CERTIFIER_EMAIL_ADD"/>
        </ns1:certifieremailAdd>
        <ns1:invalidReason>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:INVALID_REASON"/>
        </ns1:invalidReason>
        <ns1:invalidCode>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:INVALID_CODE"/>
        </ns1:invalidCode>
        <ns1:potype>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:PO_TYPE"/>
        </ns1:potype>
      </ns1:header>
      <ns1:additionalinfo>
        <ns1:docID>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:DOC_ID"/>
        </ns1:docID>
        <ns1:imageURL>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:IMAGE_URL"/>
        </ns1:imageURL>
        <ns1:Priority>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:PRIORITY"/>
        </ns1:Priority>
        <ns1:reasontype>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:INVALID_REASON_TYPE"/>
        </ns1:reasontype>
        <ns1:status>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:STATUS"/>
        </ns1:status>
        <ns1:RejectionReason>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:CERTIFIER_REJ_REASON"/>
        </ns1:RejectionReason>
        <ns1:Alternateapprover>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:CERTIFIER_REJ_COMMENTS"/>
        </ns1:Alternateapprover>
      </ns1:additionalinfo>
      <ns1:lineItems>
        <xsl:for-each select="/ns0:FetchUpdateData/ns0:FetchUpdatelineItems/ns0:lineItem">
          <ns1:lineItem>
            <ns1:LineNo>
              <xsl:value-of select="ns0:LINE_NUMBER"/>
            </ns1:LineNo>
            <ns1:lineType>
              <xsl:value-of select="ns0:LINE_TYPE"/>
            </ns1:lineType>
            <ns1:linePONumber>
              <xsl:value-of select="ns0:LINE_PO_NUM"/>
            </ns1:linePONumber>
            <ns1:POLineNumber>
              <xsl:value-of select="ns0:PO_LINE_NUM"/>
            </ns1:POLineNumber>
            <ns1:Linedescription>
              <xsl:value-of select="ns0:LINE_DESCRIPTION"/>
            </ns1:Linedescription>
            <ns1:quantity>
              <xsl:value-of select="ns0:QUANTITY"/>
            </ns1:quantity>
            <ns1:UOM>
              <xsl:value-of select="ns0:UOM"/>
            </ns1:UOM>
            <ns1:unitPrice>
              <xsl:value-of select="ns0:UNIT_PRICE"/>
            </ns1:unitPrice>
            <ns1:lineTotalAmount>
              <xsl:value-of select="ns0:LINE_TOTAL_AMOUNT"/>
            </ns1:lineTotalAmount>
            <ns1:taxrate>
              <xsl:value-of select="ns0:TAX_RATE"/>
            </ns1:taxrate>
            <ns1:taxratecode>
              <xsl:value-of select="ns0:TAX_RATE_CODE"/>
            </ns1:taxratecode>
            <ns1:projectno>
              <xsl:value-of select="ns0:PROJECT_NO"/>
            </ns1:projectno>
            <ns1:taskno>
              <xsl:value-of select="ns0:TASK_NO"/>
            </ns1:taskno>
            <ns1:expenditureOrg>
              <xsl:value-of select="ns0:EXPINDITURE_ORG"/>
            </ns1:expenditureOrg>
            <ns1:expendituredate>
              <xsl:value-of select="ns0:EXPENDITURE_DATE"/>
            </ns1:expendituredate>
            <ns1:GLNo>
              <xsl:value-of select="ns0:GL_NO"/>
            </ns1:GLNo>
          </ns1:lineItem>
        </xsl:for-each>
      </ns1:lineItems>
    </ns1:invoiceImport>
  </xsl:template>
</xsl:stylesheet>