<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/TransactionService" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns0="http://www.FetchUpdateParam.org" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl db xsd ns0 bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../xsd/TransactionService_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/TransactionService"/>
            <oracle-xsl-mapper:param name="outputParameters"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../xsd/FetchUpdateParam.xsd"/>
            <oracle-xsl-mapper:rootElement name="FetchUpdateData" namespace="http://www.FetchUpdateParam.org"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [FRI SEP 09 21:33:38 AEST 2022].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns0:FetchUpdateData>
      <ns0:FetchUpdateHeader>
        <ns0:INVOICE_ID>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:INVOICE_ID"/>
        </ns0:INVOICE_ID>
        <ns0:MODIFIED_ON>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:MODIFIED_ON"/>
        </ns0:MODIFIED_ON>
        <ns0:MODIFIED_BY>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:MODIFIED_BY"/>
        </ns0:MODIFIED_BY>
        <ns0:SUPPLIER_ID>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:SUPPLIER_ID"/>
        </ns0:SUPPLIER_ID>
        <ns0:SUPPLIER_NAME>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:SUPPLIER_NAME"/>
        </ns0:SUPPLIER_NAME>
        <ns0:SUPPLIER_NUMBER>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:SUPPLIER_NUMBER"/>
        </ns0:SUPPLIER_NUMBER>
        <ns0:SITE_ID>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:SITE_ID"/>
        </ns0:SITE_ID>
        <ns0:PO_NUMBER>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:PO_NUMBER"/>
        </ns0:PO_NUMBER>
        <ns0:TAX_AMOUNT>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:TAX_AMOUNT"/>
        </ns0:TAX_AMOUNT>
        <ns0:WITHHOLDING_TAX>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:WITHHOLDING_TAX"/>
        </ns0:WITHHOLDING_TAX>
        <ns0:INVOICE_DATE>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:INVOICE_DATE"/>
        </ns0:INVOICE_DATE>
        <ns0:CANCELLED_DATE>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:CANCELLED_DATE"/>
        </ns0:CANCELLED_DATE>
        <ns0:CANCELLED_BY>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:CANCELLED_BY"/>
        </ns0:CANCELLED_BY>
        <ns0:PROJECT_ID>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:PROJECT_ID"/>
        </ns0:PROJECT_ID>
        <ns0:INTERNAL_STATUS>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:INTERNAL_STATUS"/>
        </ns0:INTERNAL_STATUS>
        <ns0:CERTIFIER_CANCEL_BY>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:CERTIFIER_CANCEL_BY"/>
        </ns0:CERTIFIER_CANCEL_BY>
        <ns0:CERTIFIER_CANCEL_ON>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:CERTIFIER_CANCEL_ON"/>
        </ns0:CERTIFIER_CANCEL_ON>
        <ns0:ALTERNATE_APPROVER>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:ALTERNATE_APPROVER"/>
        </ns0:ALTERNATE_APPROVER>
        <ns0:DOCUMENT_TYPE>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:DOCUMENT_TYPE"/>
        </ns0:DOCUMENT_TYPE>
        <ns0:INVOICE_TYPE>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:INVOICE_TYPE"/>
        </ns0:INVOICE_TYPE>
        <ns0:IMAGE_URL>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:IMAGE_URL"/>
        </ns0:IMAGE_URL>
        <ns0:ORG_ID>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:ORG_ID"/>
        </ns0:ORG_ID>
        <ns0:INVOICE_NUMBER>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:INVOICE_NUMBER"/>
        </ns0:INVOICE_NUMBER>
        <ns0:SITE_NAME>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:SITE_NAME"/>
        </ns0:SITE_NAME>
        <ns0:TAX_REG_NUMBER>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:TAX_REG_NUMBER"/>
        </ns0:TAX_REG_NUMBER>
        <ns0:INVOICE_TOT_AMOUNT>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:INVOICE_TOT_AMOUNT"/>
        </ns0:INVOICE_TOT_AMOUNT>
        <ns0:CURRENCY_CODE>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:CURRENCY_CODE"/>
        </ns0:CURRENCY_CODE>
        <ns0:CERTIFIER_NAME>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:CERTIFIER_NAME"/>
        </ns0:CERTIFIER_NAME>
        <ns0:EMPLOYEE_NUMBER>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:EMPLOYEE_NUMBER"/>
        </ns0:EMPLOYEE_NUMBER>
        <ns0:CERTIFIER_EMAIL_ADD>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:CERTIFIER_EMAIL_ADD"/>
        </ns0:CERTIFIER_EMAIL_ADD>
        <ns0:INVALID_REASON>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:INVALID_REASON"/>
        </ns0:INVALID_REASON>
        <ns0:INVALID_CODE>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:INVALID_CODE"/>
        </ns0:INVALID_CODE>
        <ns0:PO_TYPE>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:PO_TYPE"/>
        </ns0:PO_TYPE>
        <ns0:INVALID_REASON_ID>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:INVALID_REASON_ID"/>
        </ns0:INVALID_REASON_ID>
        <ns0:INVALID_REASON_TYPE>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:INVALID_REASON_TYPE"/>
        </ns0:INVALID_REASON_TYPE>
        <ns0:INVALID_REASON_TYPE_ID>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:INVALID_REASON_TYPE_ID"/>
        </ns0:INVALID_REASON_TYPE_ID>
        <ns0:DOC_ID>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:DOC_ID"/>
        </ns0:DOC_ID>
        <ns0:PRIORITY>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:PRIORITY"/>
        </ns0:PRIORITY>
        <ns0:STATUS>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:STATUS"/>
        </ns0:STATUS>
        <ns0:AP_OPERATION_COMMENTS>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:AP_OPERATION_COMMENTS"/>
        </ns0:AP_OPERATION_COMMENTS>
        <ns0:CERTIFIER_REJ_REASON>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:CERTIFIER_REJ_REASON"/>
        </ns0:CERTIFIER_REJ_REASON>
        <ns0:CERTIFIER_REJ_COMMENTS>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:CERTIFIER_REJ_COMMENTS"/>
        </ns0:CERTIFIER_REJ_COMMENTS>
        <ns0:CERTIFIER_REASSIGN_TO>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:CERTIFIER_REASSIGN_TO"/>
        </ns0:CERTIFIER_REASSIGN_TO>
        <ns0:CERTIFIER_REASSIGN_COMMENTS>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:CERTIFIER_REASSIGN_COMMENTS"/>
        </ns0:CERTIFIER_REASSIGN_COMMENTS>
        <ns0:CERTIFIER_APPROVE_COMMENTS>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:CERTIFIER_APPROVE_COMMENTS"/>
        </ns0:CERTIFIER_APPROVE_COMMENTS>
        <ns0:CERTIFIER_BY>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:CERTIFIER_BY"/>
        </ns0:CERTIFIER_BY>
        <ns0:ATTR1>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:ATTR1"/>
        </ns0:ATTR1>
        <ns0:ATTR2>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:ATTR2"/>
        </ns0:ATTR2>
        <ns0:ATTR3>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:ATTR3"/>
        </ns0:ATTR3>
        <ns0:ATTR4>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:ATTR4"/>
        </ns0:ATTR4>
        <ns0:ATTR5>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:ATTR5"/>
        </ns0:ATTR5>
        <ns0:ATTR6>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:ATTR6"/>
        </ns0:ATTR6>
        <ns0:ATTR7>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:ATTR7"/>
        </ns0:ATTR7>
        <ns0:ATTR8>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:ATTR8"/>
        </ns0:ATTR8>
        <ns0:ATTR9>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:ATTR9"/>
        </ns0:ATTR9>
        <ns0:ATTR10>
          <xsl:value-of select="/db:OutputParameters/db:IO_INV_HEADER/db:ATTR10"/>
        </ns0:ATTR10>
      </ns0:FetchUpdateHeader>
      <ns0:FetchUpdatelineItems>
        <xsl:for-each select="/db:OutputParameters/db:IO_INV_LINE/db:IO_INV_LINE_ITEM">
          <ns0:lineItem>
            <ns0:INVOICE_ID>
              <xsl:value-of select="db:INVOICE_ID"/>
            </ns0:INVOICE_ID>
            <ns0:LINE_NUMBER>
              <xsl:value-of select="db:LINE_NUMBER"/>
            </ns0:LINE_NUMBER>
            <ns0:LINE_TYPE>
              <xsl:value-of select="db:LINE_TYPE"/>
            </ns0:LINE_TYPE>
            <ns0:LINE_PO_NUM>
              <xsl:value-of select="db:LINE_PO_NUM"/>
            </ns0:LINE_PO_NUM>
            <ns0:PO_LINE_NUM>
              <xsl:value-of select="db:PO_LINE_NUM"/>
            </ns0:PO_LINE_NUM>
            <ns0:LINE_DESCRIPTION>
              <xsl:value-of select="db:LINE_DESCRIPTION"/>
            </ns0:LINE_DESCRIPTION>
            <ns0:QUANTITY>
              <xsl:value-of select="db:QUANTITY"/>
            </ns0:QUANTITY>
            <ns0:UOM>
              <xsl:value-of select="db:UOM"/>
            </ns0:UOM>
            <ns0:UNIT_PRICE>
              <xsl:value-of select="db:UNIT_PRICE"/>
            </ns0:UNIT_PRICE>
            <ns0:LINE_TOTAL_AMOUNT>
              <xsl:value-of select="db:LINE_TOTAL_AMOUNT"/>
            </ns0:LINE_TOTAL_AMOUNT>
            <ns0:TAX_RATE>
              <xsl:value-of select="db:TAX_RATE"/>
            </ns0:TAX_RATE>
            <ns0:TAX_RATE_CODE>
              <xsl:value-of select="db:TAX_RATE_CODE"/>
            </ns0:TAX_RATE_CODE>
            <ns0:PROJECT_NO>
              <xsl:value-of select="db:PROJECT_NO"/>
            </ns0:PROJECT_NO>
            <ns0:TASK_NO>
              <xsl:value-of select="db:TASK_NO"/>
            </ns0:TASK_NO>
            <ns0:EXPINDITURE_ORG>
              <xsl:value-of select="db:EXPINDITURE_ORG"/>
            </ns0:EXPINDITURE_ORG>
            <ns0:EXPENDITURE_DATE>
              <xsl:value-of select="db:EXPENDITURE_DATE"/>
            </ns0:EXPENDITURE_DATE>
            <ns0:GL_NO>
              <xsl:value-of select="db:GL_NO"/>
            </ns0:GL_NO>
            <ns0:ATTR1>
              <xsl:value-of select="db:ATTR1"/>
            </ns0:ATTR1>
            <ns0:ATTR2>
              <xsl:value-of select="db:ATTR2"/>
            </ns0:ATTR2>
            <ns0:ATTR3>
              <xsl:value-of select="db:ATTR3"/>
            </ns0:ATTR3>
            <ns0:ATTR4>
              <xsl:value-of select="db:ATTR4"/>
            </ns0:ATTR4>
            <ns0:ATTR5>
              <xsl:value-of select="db:ATTR5"/>
            </ns0:ATTR5>
            <ns0:ATTR6>
              <xsl:value-of select="db:ATTR6"/>
            </ns0:ATTR6>
            <ns0:ATTR7>
              <xsl:value-of select="db:ATTR7"/>
            </ns0:ATTR7>
            <ns0:ATTR8>
              <xsl:value-of select="db:ATTR8"/>
            </ns0:ATTR8>
            <ns0:ATTR9>
              <xsl:value-of select="db:ATTR9"/>
            </ns0:ATTR9>
            <ns0:ATTR10>
              <xsl:value-of select="db:ATTR10"/>
            </ns0:ATTR10>
          </ns0:lineItem>
        </xsl:for-each>
      </ns0:FetchUpdatelineItems>
    </ns0:FetchUpdateData>
  </xsl:template>
</xsl:stylesheet>