<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/TransactionService" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns0="http://www.InvoiceData.org" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl xsd ns0 db bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../xsd/InvoiceData.xsd"/>
            <oracle-xsl-mapper:rootElement name="invoiceImport" namespace="http://www.InvoiceData.org"/>
            <oracle-xsl-mapper:param name="WFRInputPDO"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../xsd/TransactionService_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/TransactionService"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [FRI SEP 09 21:33:38 AEST 2022].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <db:InputParameters>
           <db:IO_INV_HEADER>
        <db:SUPPLIER_ID>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:supplierId"/>
        </db:SUPPLIER_ID>
        <db:SUPPLIER_NAME>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:supplierName"/>
        </db:SUPPLIER_NAME>
        <db:SUPPLIER_NUMBER>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:supplierNumber"/>
        </db:SUPPLIER_NUMBER>
        <db:SITE_ID>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:SiteID"/>
        </db:SITE_ID>
        <db:PO_NUMBER>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:PONumber"/>
        </db:PO_NUMBER>
        <db:TAX_AMOUNT>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:tax"/>
        </db:TAX_AMOUNT>
        <db:WITHHOLDING_TAX>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:withholdingTax"/>
        </db:WITHHOLDING_TAX>
        <db:INVOICE_DATE>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:invoiceDate"/>
        </db:INVOICE_DATE>
        <db:ALTERNATE_APPROVER>
          <xsl:value-of select="/ns0:invoiceImport/ns0:additionalinfo/ns0:Alternateapprover"/>
        </db:ALTERNATE_APPROVER>
        <db:DOCUMENT_TYPE>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:documentType"/>
        </db:DOCUMENT_TYPE>
        <db:INVOICE_TYPE>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:invoiceType"/>
        </db:INVOICE_TYPE>
        <db:IMAGE_URL>
          <xsl:value-of select="/ns0:invoiceImport/ns0:additionalinfo/ns0:imageURL"/>
        </db:IMAGE_URL>
        <db:ORG_ID>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:orgID"/>
        </db:ORG_ID>
        <db:INVOICE_NUMBER>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:invoiceNumber"/>
        </db:INVOICE_NUMBER>
        <db:SITE_NAME>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:SiteName"/>
        </db:SITE_NAME>
        <db:TAX_REG_NUMBER>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:Taxregistrationnumber"/>
        </db:TAX_REG_NUMBER>
        <db:INVOICE_TOT_AMOUNT>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:invoiceTotalAmount"/>
        </db:INVOICE_TOT_AMOUNT>
        <db:CURRENCY_CODE>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:currencyCode"/>
        </db:CURRENCY_CODE>
        <db:CERTIFIER_NAME>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:certifierName"/>
        </db:CERTIFIER_NAME>
        <db:EMPLOYEE_NUMBER>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:employeeno"/>
        </db:EMPLOYEE_NUMBER>
        <db:CERTIFIER_EMAIL_ADD>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:certifieremailAdd"/>
        </db:CERTIFIER_EMAIL_ADD>
        <db:INVALID_REASON>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:invalidReason"/>
        </db:INVALID_REASON>
        <db:INVALID_CODE>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:invalidCode"/>
        </db:INVALID_CODE>
        <db:PO_TYPE>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:potype"/>
        </db:PO_TYPE>
        <db:INVALID_REASON_TYPE>
          <xsl:value-of select="/ns0:invoiceImport/ns0:additionalinfo/ns0:reasontype"/>
        </db:INVALID_REASON_TYPE>
        <db:DOC_ID>
          <xsl:value-of select="/ns0:invoiceImport/ns0:additionalinfo/ns0:docID"/>
        </db:DOC_ID>
        <db:PRIORITY>
          <xsl:value-of select="/ns0:invoiceImport/ns0:additionalinfo/ns0:Priority"/>
        </db:PRIORITY>
        <db:STATUS>
          <xsl:value-of select="/ns0:invoiceImport/ns0:additionalinfo/ns0:status"/>
        </db:STATUS>
        <db:CERTIFIER_REJ_REASON>
          <xsl:value-of select="/ns0:invoiceImport/ns0:additionalinfo/ns0:RejectionReason"/>
        </db:CERTIFIER_REJ_REASON>
        <db:CERTIFIER_REJ_COMMENTS>
          <xsl:value-of select="/ns0:invoiceImport/ns0:additionalinfo/ns0:CertifierComments"/>
        </db:CERTIFIER_REJ_COMMENTS>
      </db:IO_INV_HEADER>
      <db:IO_INV_LINE>
        <xsl:for-each select="/ns0:invoiceImport/ns0:lineItems/ns0:lineItem">
          <db:IO_INV_LINE_ITEM>
            <db:LINE_NUMBER>
              <xsl:value-of select="ns0:LineNo"/>
            </db:LINE_NUMBER>
            <db:LINE_TYPE>
              <xsl:value-of select="ns0:lineType"/>
            </db:LINE_TYPE>
            <db:LINE_PO_NUM>
              <xsl:value-of select="ns0:linePONumber"/>
            </db:LINE_PO_NUM>
            <db:PO_LINE_NUM>
              <xsl:value-of select="ns0:POLineNumber"/>
            </db:PO_LINE_NUM>
            <db:LINE_DESCRIPTION>
              <xsl:value-of select="ns0:Linedescription"/>
            </db:LINE_DESCRIPTION>
            <db:QUANTITY>
              <xsl:value-of select="ns0:quantity"/>
            </db:QUANTITY>
            <db:UOM>
              <xsl:value-of select="ns0:UOM"/>
            </db:UOM>
            <db:UNIT_PRICE>
              <xsl:value-of select="ns0:unitPrice"/>
            </db:UNIT_PRICE>
            <db:LINE_TOTAL_AMOUNT>
              <xsl:value-of select="ns0:lineTotalAmount"/>
            </db:LINE_TOTAL_AMOUNT>
            <db:TAX_RATE>
              <xsl:value-of select="ns0:taxrate"/>
            </db:TAX_RATE>
            <db:TAX_RATE_CODE>
              <xsl:value-of select="ns0:taxratecode"/>
            </db:TAX_RATE_CODE>
            <db:PROJECT_NO>
              <xsl:value-of select="ns0:projectno"/>
            </db:PROJECT_NO>
            <db:TASK_NO>
              <xsl:value-of select="ns0:taskno"/>
            </db:TASK_NO>
            <db:EXPINDITURE_ORG>
              <xsl:value-of select="ns0:expenditureOrg"/>
            </db:EXPINDITURE_ORG>
            <db:EXPENDITURE_DATE>
              <xsl:value-of select="ns0:expendituredate"/>
            </db:EXPENDITURE_DATE>
            <db:GL_NO>
              <xsl:value-of select="ns0:GLNo"/>
            </db:GL_NO>
          </db:IO_INV_LINE_ITEM>
        </xsl:for-each>
      </db:IO_INV_LINE>
      <db:I_TRANSACTION_TYPE>
        <xsl:text disable-output-escaping="no">INSERT</xsl:text>
      </db:I_TRANSACTION_TYPE>
    </db:InputParameters>
  </xsl:template>
</xsl:stylesheet>