
package ap.quantas.com.imaging.documentSearchService;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ImagingException", targetNamespace = "http://imaging.oracle/")
public class ImagingException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ImagingFaultInfo faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ImagingException(String message, ImagingFaultInfo faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ImagingException(String message, ImagingFaultInfo faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ap.quantas.com.imaging.documentSearchService.ImagingFaultInfo
     */
    public ImagingFaultInfo getFaultInfo() {
        return faultInfo;
    }

}
