
package ap.quantas.com.imaging.documentSearchService;

import ap.quantas.com.Utility;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
//same wsdl for dev n sit-psp-@WebServiceClient(name = "SearchService", targetNamespace = "http://imaging.oracle/", wsdlLocation = "http://eqdev-capture1.qantas.com.au:19000/imaging/ws/SearchService?wsdl")
//WebServiceClient(name = "SearchService", targetNamespace = "http://imaging.oracle/", wsdlLocation = "http://eqprod-capture1.qantas.com.au:19000/imaging/ws/SearchService?wsdl")
@WebServiceClient(name = "SearchService", targetNamespace = "http://imaging.oracle/", wsdlLocation = "http://eqprod-capture1.qantas.com.au:16033/imaging/ws/SearchService?wsdl")
public class SearchService_Service
    extends Service
{

    private final static URL SEARCHSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ap.quantas.com.imaging.documentSearchService.SearchService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ap.quantas.com.imaging.documentSearchService.SearchService_Service.class.getResource(".");
            url = new URL(baseUrl, Utility.resolveExpression("#{ApOperationBean.propertyLoader.properties['IMAGING_DOCUMENT_SEARCH_SERVICE_WSDL']}").toString());
           // url = new URL(baseUrl, "http://eqprod-capture1.qantas.com.au:19000/imaging/ws/SearchService?wsdl");
//           url = new URL(baseUrl, "http://eqprod-capture1.qantas.com.au:16033/imaging/ws/SearchService?wsdl");

        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/332914/Desktop/DocRetrieveSvc/SearchService.xml', retrying as a local file");
            logger.warning(e.getMessage());
        }
        catch (Exception e) {
                   System.out.println(e);
               }
        
        SEARCHSERVICE_WSDL_LOCATION = url;
    }

    public SearchService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SearchService_Service() {
        super(SEARCHSERVICE_WSDL_LOCATION, new QName("http://imaging.oracle/", "SearchService"));
    }

    /**
     * 
     * @return
     *     returns SearchService
     */
    @WebEndpoint(name = "SearchServicePort")
    public SearchService getSearchServicePort() {
        return super.getPort(new QName("http://imaging.oracle/", "SearchServicePort"), SearchService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchService
     */
    @WebEndpoint(name = "SearchServicePort")
    public SearchService getSearchServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://imaging.oracle/", "SearchServicePort"), SearchService.class, features);
    }

}
