<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns0="http://www.InvoiceData.org" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl xsd ns0 bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../xsd/InvoiceData.xsd"/>
            <oracle-xsl-mapper:rootElement name="invoiceImport" namespace="http://www.InvoiceData.org"/>
            <oracle-xsl-mapper:param name="WFRInputPDO"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../xsd/InvoiceData.xsd"/>
            <oracle-xsl-mapper:rootElement name="invoiceImport" namespace="http://www.InvoiceData.org"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [TUE APR 19 16:34:21 AEST 2022].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns0:invoiceImport>
      <ns0:header>
        <ns0:documentType>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:documentType"/>
        </ns0:documentType>
        <ns0:invoiceType>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:invoiceType"/>
        </ns0:invoiceType>
        <ns0:orgID>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:orgID"/>
        </ns0:orgID>
        <ns0:invoiceNumber>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:invoiceNumber"/>
        </ns0:invoiceNumber>
        <ns0:invoiceDate>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:invoiceDate"/>
        </ns0:invoiceDate>
        <ns0:supplierId>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:supplierId"/>
        </ns0:supplierId>
        <ns0:supplierName>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:supplierName"/>
        </ns0:supplierName>
        <ns0:supplierNumber>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:supplierNumber"/>
        </ns0:supplierNumber>
        <ns0:SiteID>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:SiteID"/>
        </ns0:SiteID>
        <ns0:SiteName>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:SiteName"/>
        </ns0:SiteName>
        <ns0:PONumber>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:PONumber"/>
        </ns0:PONumber>
        <ns0:Taxregistrationnumber>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:Taxregistrationnumber"/>
        </ns0:Taxregistrationnumber>
        <ns0:tax>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:tax"/>
        </ns0:tax>
        <ns0:withholdingTax>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:withholdingTax"/>
        </ns0:withholdingTax>
        <ns0:invoiceTotalAmount>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:invoiceTotalAmount"/>
        </ns0:invoiceTotalAmount>
        <ns0:currencyCode>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:currencyCode"/>
        </ns0:currencyCode>
        <ns0:certifierName>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:certifierName"/>
        </ns0:certifierName>
        <ns0:employeeno>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:employeeno"/>
        </ns0:employeeno>
        <ns0:certifieremailAdd>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:certifieremailAdd"/>
        </ns0:certifieremailAdd>
        <ns0:invalidReason>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:invalidReason"/>
        </ns0:invalidReason>
        <ns0:invalidCode>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:invalidCode"/>
        </ns0:invalidCode>
        <ns0:potype>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:potype"/>
        </ns0:potype>
      </ns0:header>
      <ns0:additionalinfo>
        <ns0:docID>
          <xsl:value-of select="/ns0:invoiceImport/ns0:additionalinfo/ns0:docID"/>
        </ns0:docID>
        <ns0:imageURL>
          <xsl:value-of select="/ns0:invoiceImport/ns0:additionalinfo/ns0:imageURL"/>
        </ns0:imageURL>
        <ns0:Priority>
          <xsl:value-of select="/ns0:invoiceImport/ns0:additionalinfo/ns0:Priority"/>
        </ns0:Priority>
        <ns0:reasontype>
          <xsl:value-of select="/ns0:invoiceImport/ns0:additionalinfo/ns0:reasontype"/>
        </ns0:reasontype>
        <ns0:status>
          <xsl:value-of select="/ns0:invoiceImport/ns0:additionalinfo/ns0:status"/>
        </ns0:status>
        <ns0:RejectionReason>
          <xsl:value-of select="/ns0:invoiceImport/ns0:additionalinfo/ns0:RejectionReason"/>
        </ns0:RejectionReason>
        <ns0:CertifierComments>
          <xsl:value-of select="/ns0:invoiceImport/ns0:additionalinfo/ns0:CertifierComments"/>
        </ns0:CertifierComments>
        <ns0:Alternateapprover>
          <xsl:value-of select="/ns0:invoiceImport/ns0:additionalinfo/ns0:Alternateapprover"/>
        </ns0:Alternateapprover>
        <ns0:LineTotalAmount>
          <xsl:value-of select="sum(/ns0:invoiceImport/ns0:lineItems/ns0:lineItem/ns0:LineNo)"/>
        </ns0:LineTotalAmount>
        <ns0:TaxTotalAmount>
          <xsl:value-of select="format-number(number(sum(/ns0:invoiceImport/ns0:lineItems/ns0:lineItem/ns0:unitPrice) * sum(/ns0:invoiceImport/ns0:lineItems/ns0:lineItem/ns0:quantity)),&quot;###0.00&quot;)"/>
        </ns0:TaxTotalAmount>
      </ns0:additionalinfo>
      <ns0:lineItems>
        <xsl:for-each select="/ns0:invoiceImport/ns0:lineItems/ns0:lineItem">
          <ns0:lineItem>
            <ns0:LineNo>
              <xsl:value-of select="ns0:LineNo"/>
            </ns0:LineNo>
            <ns0:lineType>
              <xsl:value-of select="ns0:lineType"/>
            </ns0:lineType>
            <ns0:linePONumber>
              <xsl:value-of select="ns0:linePONumber"/>
            </ns0:linePONumber>
            <ns0:POLineNumber>
              <xsl:value-of select="ns0:POLineNumber"/>
            </ns0:POLineNumber>
            <ns0:Linedescription>
              <xsl:value-of select="ns0:Linedescription"/>
            </ns0:Linedescription>
            <ns0:quantity>
              <xsl:value-of select="ns0:quantity"/>
            </ns0:quantity>
            <ns0:UOM>
              <xsl:value-of select="ns0:UOM"/>
            </ns0:UOM>
            <ns0:unitPrice>
              <xsl:value-of select="ns0:unitPrice"/>
            </ns0:unitPrice>
            <ns0:lineTotalAmount>
              <xsl:value-of select="ns0:lineTotalAmount"/>
            </ns0:lineTotalAmount>
            <ns0:taxrate>
              <xsl:value-of select="ns0:taxrate"/>
            </ns0:taxrate>
            <ns0:taxratecode>
              <xsl:value-of select="ns0:taxratecode"/>
            </ns0:taxratecode>
            <ns0:projectno>
              <xsl:value-of select="ns0:projectno"/>
            </ns0:projectno>
            <ns0:taskno>
              <xsl:value-of select="ns0:taskno"/>
            </ns0:taskno>
            <ns0:expenditureOrg>
              <xsl:value-of select="ns0:expenditureOrg"/>
            </ns0:expenditureOrg>
            <ns0:expendituredate>
              <xsl:value-of select="ns0:expendituredate"/>
            </ns0:expendituredate>
            <ns0:GLNo>
              <xsl:value-of select="ns0:GLNo"/>
            </ns0:GLNo>
          </ns0:lineItem>
        </xsl:for-each>
      </ns0:lineItems>
    </ns0:invoiceImport>
  </xsl:template>
</xsl:stylesheet>