<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/ValidationService" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns0="http://www.InvoiceData.org" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl xsd ns0 db bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../xsd/InvoiceData.xsd"/>
            <oracle-xsl-mapper:rootElement name="invoiceImport" namespace="http://www.InvoiceData.org"/>
            <oracle-xsl-mapper:param name="WFRInputPDO"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../xsd/ValidationService_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/ValidationService"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [TUE APR 19 16:34:21 AEST 2022].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <db:InputParameters>
      <db:P_INVOICE_IN>
        <db:DOCUMENTTYPE>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:documentType"/>
        </db:DOCUMENTTYPE>
        <db:INVOICETYPE>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:invoiceType"/>
        </db:INVOICETYPE>
        <db:ORGID>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:orgID"/>
        </db:ORGID>
        <db:INVOICENUMBER>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:invoiceNumber"/>
        </db:INVOICENUMBER>
        <db:INVOICEDATE>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:invoiceDate"/>
        </db:INVOICEDATE>
        <db:SUPPLIERID>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:supplierId"/>
        </db:SUPPLIERID>
        <db:SUPPLIERNAME>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:supplierName"/>
        </db:SUPPLIERNAME>
        <db:SUPPLIERNUMBER>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:supplierNumber"/>
        </db:SUPPLIERNUMBER>
        <db:SITEID>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:SiteID"/>
        </db:SITEID>
        <db:SITENAME>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:SiteName"/>
        </db:SITENAME>
        <db:PONUMBER>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:PONumber"/>
        </db:PONUMBER>
        <db:TAXREGISTRATIONNUMBER>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:Taxregistrationnumber"/>
        </db:TAXREGISTRATIONNUMBER>
        <db:TAX>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:tax"/>
        </db:TAX>
        <db:WITHHOLDINGTAX>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:withholdingTax"/>
        </db:WITHHOLDINGTAX>
        <db:INVOICETOTALAMOUNT>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:invoiceTotalAmount"/>
        </db:INVOICETOTALAMOUNT>
        <db:CURRENCYCODE>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:currencyCode"/>
        </db:CURRENCYCODE>
        <db:CERTIFIERNAME>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:certifierName"/>
        </db:CERTIFIERNAME>
        <db:EMPLOYEENO>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:employeeno"/>
        </db:EMPLOYEENO>
        <db:CERTIFIEREMAILADD>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:certifieremailAdd"/>
        </db:CERTIFIEREMAILADD>
        <db:INVALIDREASON>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:invalidReason"/>
        </db:INVALIDREASON>
        <db:INVALIDCODE>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:invalidCode"/>
        </db:INVALIDCODE>
        <db:POTYPE>
          <xsl:value-of select="/ns0:invoiceImport/ns0:header/ns0:potype"/>
        </db:POTYPE>
        <db:IMAGEURL>
          <xsl:value-of select="/ns0:invoiceImport/ns0:additionalinfo/ns0:imageURL"/>
        </db:IMAGEURL>
        <db:PRIORITY>
          <xsl:value-of select="/ns0:invoiceImport/ns0:additionalinfo/ns0:Priority"/>
        </db:PRIORITY>
        <db:REASONTYPE>
          <xsl:value-of select="/ns0:invoiceImport/ns0:additionalinfo/ns0:reasontype"/>
        </db:REASONTYPE>
        <db:STATUS>
          <xsl:value-of select="/ns0:invoiceImport/ns0:additionalinfo/ns0:status"/>
        </db:STATUS>
        <db:REJECTIONREASON>
          <xsl:value-of select="/ns0:invoiceImport/ns0:additionalinfo/ns0:RejectionReason"/>
        </db:REJECTIONREASON>
        <db:CERTIFIERCOMMENTS>
          <xsl:value-of select="/ns0:invoiceImport/ns0:additionalinfo/ns0:CertifierComments"/>
        </db:CERTIFIERCOMMENTS>
        <db:ALTERNATEAPPROVER>
          <xsl:value-of select="/ns0:invoiceImport/ns0:additionalinfo/ns0:Alternateapprover"/>
        </db:ALTERNATEAPPROVER>
      </db:P_INVOICE_IN>
      <db:P_INV_LINE>
        <xsl:for-each select="/ns0:invoiceImport/ns0:lineItems/ns0:lineItem">
          <db:P_INV_LINE_ITEM>
            <db:LINENO>
              <xsl:value-of select="ns0:LineNo"/>
            </db:LINENO>
            <db:LINETYPE>
              <xsl:value-of select="ns0:lineType"/>
            </db:LINETYPE>
            <db:LINEPONUMBER>
              <xsl:value-of select="ns0:linePONumber"/>
            </db:LINEPONUMBER>
            <db:POLINENUMBER>
              <xsl:value-of select="ns0:POLineNumber"/>
            </db:POLINENUMBER>
            <db:LINEDESCRIPTION>
              <xsl:value-of select="ns0:Linedescription"/>
            </db:LINEDESCRIPTION>
            <db:QUANTITY>
              <xsl:value-of select="ns0:quantity"/>
            </db:QUANTITY>
            <db:UOM>
              <xsl:value-of select="ns0:UOM"/>
            </db:UOM>
            <db:UNITPRICE>
              <xsl:value-of select="ns0:unitPrice"/>
            </db:UNITPRICE>
            <db:LINETOTALAMOUNT>
              <xsl:value-of select="ns0:lineTotalAmount"/>
            </db:LINETOTALAMOUNT>
            <db:TAXRATE>
              <xsl:value-of select="ns0:taxrate"/>
            </db:TAXRATE>
            <db:TAXRATECODE>
              <xsl:value-of select="ns0:taxratecode"/>
            </db:TAXRATECODE>
            <db:PROJECTNO>
              <xsl:value-of select="ns0:projectno"/>
            </db:PROJECTNO>
            <db:TASKNO>
              <xsl:value-of select="ns0:taskno"/>
            </db:TASKNO>
            <db:EXPENDITUREORG>
              <xsl:value-of select="ns0:expenditureOrg"/>
            </db:EXPENDITUREORG>
            <db:EXPENDITUREDATE>
              <xsl:value-of select="ns0:expendituredate"/>
            </db:EXPENDITUREDATE>
            <db:GLNO>
              <xsl:value-of select="ns0:GLNo"/>
            </db:GLNO>
          </db:P_INV_LINE_ITEM>
        </xsl:for-each>
      </db:P_INV_LINE>
      <db:P_CALLED_FROM>
        <xsl:text disable-output-escaping="no">WFR</xsl:text>
      </db:P_CALLED_FROM>
    </db:InputParameters>
  </xsl:template>
</xsl:stylesheet>