<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:ns1="http://www.ApprovalStatusUpdate.org" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/TransactionService" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns0="http://www.FetchUpdateParam.org" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns1 ns0 xsd db bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../xsd/FetchUpdateParam.xsd"/>
            <oracle-xsl-mapper:rootElement name="FetchUpdateData" namespace="http://www.FetchUpdateParam.org"/>
            <oracle-xsl-mapper:param name="FlexUpdatePDO"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../xsd/ApprovalStatusUpdate.xsd"/>
            <oracle-xsl-mapper:rootElement name="ApprovalStatusData" namespace="http://www.ApprovalStatusUpdate.org"/>
            <oracle-xsl-mapper:param name="ApproveStatusPDO"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../xsd/TransactionService_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/TransactionService"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [TUE APR 19 16:34:21 AEST 2022].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="ApproveStatusPDO"/>
  <xsl:template match="/">
    <db:InputParameters>
      <db:IO_INV_HEADER>
        <db:INVOICE_ID>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:INVOICE_ID"/>
        </db:INVOICE_ID>
        <db:MODIFIED_ON>
          <xsl:value-of select="$ApproveStatusPDO/ns1:ApprovalStatusData/ns1:ApprovalStatusInfo/ns1:APOperationTaskUpdatedOn"/>
        </db:MODIFIED_ON>
        <db:MODIFIED_BY>
          <xsl:value-of select="$ApproveStatusPDO/ns1:ApprovalStatusData/ns1:ApprovalStatusInfo/ns1:APOperationTaskUpdatedBy"/>
        </db:MODIFIED_BY>
        <db:SUPPLIER_ID>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:SUPPLIER_ID"/>
        </db:SUPPLIER_ID>
        <db:SUPPLIER_NAME>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:SUPPLIER_NAME"/>
        </db:SUPPLIER_NAME>
        <db:SUPPLIER_NUMBER>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:SUPPLIER_NUMBER"/>
        </db:SUPPLIER_NUMBER>
        <db:SITE_ID>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:SITE_ID"/>
        </db:SITE_ID>
        <db:PO_NUMBER>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:PO_NUMBER"/>
        </db:PO_NUMBER>
        <db:TAX_AMOUNT>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:TAX_AMOUNT"/>
        </db:TAX_AMOUNT>
        <db:WITHHOLDING_TAX>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:WITHHOLDING_TAX"/>
        </db:WITHHOLDING_TAX>
        <db:INVOICE_DATE>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:INVOICE_DATE"/>
        </db:INVOICE_DATE>
        <db:CANCELLED_DATE>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:CANCELLED_DATE"/>
        </db:CANCELLED_DATE>
        <db:CANCELLED_BY>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:CANCELLED_BY"/>
        </db:CANCELLED_BY>
        <db:PROJECT_ID>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:PROJECT_ID"/>
        </db:PROJECT_ID>
        <db:INTERNAL_STATUS>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:INTERNAL_STATUS"/>
        </db:INTERNAL_STATUS>
        <db:CERTIFIER_CANCEL_BY>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:CERTIFIER_CANCEL_BY"/>
        </db:CERTIFIER_CANCEL_BY>
        <db:CERTIFIER_CANCEL_ON>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:CERTIFIER_CANCEL_ON"/>
        </db:CERTIFIER_CANCEL_ON>
        <db:ALTERNATE_APPROVER>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:ALTERNATE_APPROVER"/>
        </db:ALTERNATE_APPROVER>
        <db:DOCUMENT_TYPE>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:DOCUMENT_TYPE"/>
        </db:DOCUMENT_TYPE>
        <db:INVOICE_TYPE>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:INVOICE_TYPE"/>
        </db:INVOICE_TYPE>
        <db:IMAGE_URL>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:IMAGE_URL"/>
        </db:IMAGE_URL>
        <db:ORG_ID>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:ORG_ID"/>
        </db:ORG_ID>
        <db:INVOICE_NUMBER>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:INVOICE_NUMBER"/>
        </db:INVOICE_NUMBER>
        <db:SITE_NAME>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:SITE_NAME"/>
        </db:SITE_NAME>
        <db:TAX_REG_NUMBER>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:TAX_REG_NUMBER"/>
        </db:TAX_REG_NUMBER>
        <db:INVOICE_TOT_AMOUNT>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:INVOICE_TOT_AMOUNT"/>
        </db:INVOICE_TOT_AMOUNT>
        <db:CURRENCY_CODE>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:CURRENCY_CODE"/>
        </db:CURRENCY_CODE>
        <db:CERTIFIER_NAME>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:CERTIFIER_NAME"/>
        </db:CERTIFIER_NAME>
        <db:EMPLOYEE_NUMBER>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:EMPLOYEE_NUMBER"/>
        </db:EMPLOYEE_NUMBER>
        <db:CERTIFIER_EMAIL_ADD>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:CERTIFIER_EMAIL_ADD"/>
        </db:CERTIFIER_EMAIL_ADD>
        <db:INVALID_REASON>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:INVALID_REASON"/>
        </db:INVALID_REASON>
        <db:INVALID_CODE>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:INVALID_CODE"/>
        </db:INVALID_CODE>
        <db:PO_TYPE>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:PO_TYPE"/>
        </db:PO_TYPE>
        <db:INVALID_REASON_ID>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:INVALID_REASON_ID"/>
        </db:INVALID_REASON_ID>
        <db:INVALID_REASON_TYPE>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:INVALID_REASON_TYPE"/>
        </db:INVALID_REASON_TYPE>
        <db:INVALID_REASON_TYPE_ID>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:INVALID_REASON_TYPE_ID"/>
        </db:INVALID_REASON_TYPE_ID>
        <db:DOC_ID>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:DOC_ID"/>
        </db:DOC_ID>
        <db:PRIORITY>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:PRIORITY"/>
        </db:PRIORITY>
        <db:STATUS>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:STATUS"/>
        </db:STATUS>
        <db:AP_OPERATION_COMMENTS>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:AP_OPERATION_COMMENTS"/>
        </db:AP_OPERATION_COMMENTS>
        <db:CERTIFIER_REJ_REASON>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:CERTIFIER_REJ_REASON"/>
        </db:CERTIFIER_REJ_REASON>
        <db:CERTIFIER_REJ_COMMENTS>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:CERTIFIER_REJ_COMMENTS"/>
        </db:CERTIFIER_REJ_COMMENTS>
        <db:CERTIFIER_REASSIGN_TO>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:CERTIFIER_REASSIGN_TO"/>
        </db:CERTIFIER_REASSIGN_TO>
        <db:CERTIFIER_REASSIGN_COMMENTS>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:CERTIFIER_REASSIGN_COMMENTS"/>
        </db:CERTIFIER_REASSIGN_COMMENTS>
        <db:CERTIFIER_APPROVE_COMMENTS>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:CERTIFIER_APPROVE_COMMENTS"/>
        </db:CERTIFIER_APPROVE_COMMENTS>
        <db:CERTIFIER_BY>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:CERTIFIER_BY"/>
        </db:CERTIFIER_BY>
        <db:ATTR1>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:ATTR1"/>
        </db:ATTR1>
        <db:ATTR2>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:ATTR2"/>
        </db:ATTR2>
        <db:ATTR3>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:ATTR3"/>
        </db:ATTR3>
        <db:ATTR4>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:ATTR4"/>
        </db:ATTR4>
        <db:ATTR5>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:ATTR5"/>
        </db:ATTR5>
        <db:ATTR6>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:ATTR6"/>
        </db:ATTR6>
        <db:ATTR7>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:ATTR7"/>
        </db:ATTR7>
        <db:ATTR8>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:ATTR8"/>
        </db:ATTR8>
        <db:ATTR9>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:ATTR9"/>
        </db:ATTR9>
        <db:ATTR10>
          <xsl:value-of select="/ns0:FetchUpdateData/ns0:FetchUpdateHeader/ns0:ATTR10"/>
        </db:ATTR10>
      </db:IO_INV_HEADER>
      <db:IO_INV_LINE>
        <xsl:for-each select="/ns0:FetchUpdateData/ns0:FetchUpdatelineItems/ns0:lineItem">
          <db:IO_INV_LINE_ITEM>
            <db:INVOICE_ID>
              <xsl:value-of select="ns0:INVOICE_ID"/>
            </db:INVOICE_ID>
            <db:LINE_NUMBER>
              <xsl:value-of select="ns0:LINE_NUMBER"/>
            </db:LINE_NUMBER>
            <db:LINE_TYPE>
              <xsl:value-of select="ns0:LINE_TYPE"/>
            </db:LINE_TYPE>
            <db:LINE_PO_NUM>
              <xsl:value-of select="ns0:LINE_PO_NUM"/>
            </db:LINE_PO_NUM>
            <db:PO_LINE_NUM>
              <xsl:value-of select="ns0:PO_LINE_NUM"/>
            </db:PO_LINE_NUM>
            <db:LINE_DESCRIPTION>
              <xsl:value-of select="ns0:LINE_DESCRIPTION"/>
            </db:LINE_DESCRIPTION>
            <db:QUANTITY>
              <xsl:value-of select="ns0:QUANTITY"/>
            </db:QUANTITY>
            <db:UOM>
              <xsl:value-of select="ns0:UOM"/>
            </db:UOM>
            <db:UNIT_PRICE>
              <xsl:value-of select="ns0:UNIT_PRICE"/>
            </db:UNIT_PRICE>
            <db:LINE_TOTAL_AMOUNT>
              <xsl:value-of select="ns0:LINE_TOTAL_AMOUNT"/>
            </db:LINE_TOTAL_AMOUNT>
            <db:TAX_RATE>
              <xsl:value-of select="ns0:TAX_RATE"/>
            </db:TAX_RATE>
            <db:TAX_RATE_CODE>
              <xsl:value-of select="ns0:TAX_RATE_CODE"/>
            </db:TAX_RATE_CODE>
            <db:PROJECT_NO>
              <xsl:value-of select="ns0:PROJECT_NO"/>
            </db:PROJECT_NO>
            <db:TASK_NO>
              <xsl:value-of select="ns0:TASK_NO"/>
            </db:TASK_NO>
            <db:EXPINDITURE_ORG>
              <xsl:value-of select="ns0:EXPINDITURE_ORG"/>
            </db:EXPINDITURE_ORG>
            <db:EXPENDITURE_DATE>
              <xsl:value-of select="ns0:EXPENDITURE_DATE"/>
            </db:EXPENDITURE_DATE>
            <db:GL_NO>
              <xsl:value-of select="ns0:GL_NO"/>
            </db:GL_NO>
            <db:ATTR1>
              <xsl:value-of select="ns0:ATTR1"/>
            </db:ATTR1>
            <db:ATTR2>
              <xsl:value-of select="ns0:ATTR2"/>
            </db:ATTR2>
            <db:ATTR3>
              <xsl:value-of select="ns0:ATTR3"/>
            </db:ATTR3>
            <db:ATTR4>
              <xsl:value-of select="ns0:ATTR4"/>
            </db:ATTR4>
            <db:ATTR5>
              <xsl:value-of select="ns0:ATTR5"/>
            </db:ATTR5>
            <db:ATTR6>
              <xsl:value-of select="ns0:ATTR6"/>
            </db:ATTR6>
            <db:ATTR7>
              <xsl:value-of select="ns0:ATTR7"/>
            </db:ATTR7>
            <db:ATTR8>
              <xsl:value-of select="ns0:ATTR8"/>
            </db:ATTR8>
            <db:ATTR9>
              <xsl:value-of select="ns0:ATTR9"/>
            </db:ATTR9>
            <db:ATTR10>
              <xsl:value-of select="ns0:ATTR10"/>
            </db:ATTR10>
          </db:IO_INV_LINE_ITEM>
        </xsl:for-each>
      </db:IO_INV_LINE>
      <db:I_TRANSACTION_TYPE>
        <xsl:text disable-output-escaping="no">UPDATE</xsl:text>
      </db:I_TRANSACTION_TYPE>
    </db:InputParameters>
  </xsl:template>
</xsl:stylesheet>