<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://www.ApprovalStatusUpdate.org" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/ValidationService" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns1="http://www.FetchUpdateParam.org" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns0 db xsd ns1 bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../xsd/ValidationService_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/ValidationService"/>
            <oracle-xsl-mapper:param name="outputParameters"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../xsd/ApprovalStatusUpdate.xsd"/>
            <oracle-xsl-mapper:rootElement name="ApprovalStatusData" namespace="http://www.ApprovalStatusUpdate.org"/>
            <oracle-xsl-mapper:param name="ApproveStatusPDO"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../xsd/FetchUpdateParam.xsd"/>
            <oracle-xsl-mapper:rootElement name="FetchUpdateData" namespace="http://www.FetchUpdateParam.org"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [TUE APR 19 16:34:21 AEST 2022].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="ApproveStatusPDO"/>
  <xsl:template match="/">
    <ns1:FetchUpdateData>
      <ns1:FetchUpdateHeader>
        <ns1:INVOICE_ID>
          <xsl:value-of select="$ApproveStatusPDO/ns0:ApprovalStatusData/ns0:ApprovalStatusInfo/ns0:InvoiceID"/>
        </ns1:INVOICE_ID>
        <ns1:SUPPLIER_ID>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:SUPPLIERID"/>
        </ns1:SUPPLIER_ID>
        <ns1:SUPPLIER_NAME>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:SUPPLIERNAME"/>
        </ns1:SUPPLIER_NAME>
        <ns1:SUPPLIER_NUMBER>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:SUPPLIERNUMBER"/>
        </ns1:SUPPLIER_NUMBER>
        <ns1:SITE_ID>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:SITEID"/>
        </ns1:SITE_ID>
        <ns1:PO_NUMBER>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:PONUMBER"/>
        </ns1:PO_NUMBER>
        <ns1:TAX_AMOUNT>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:TAX"/>
        </ns1:TAX_AMOUNT>
        <ns1:WITHHOLDING_TAX>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:WITHHOLDINGTAX"/>
        </ns1:WITHHOLDING_TAX>
        <ns1:INVOICE_DATE>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:INVOICEDATE"/>
        </ns1:INVOICE_DATE>
        <ns1:ALTERNATE_APPROVER>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:ALTERNATEAPPROVER"/>
        </ns1:ALTERNATE_APPROVER>
        <ns1:DOCUMENT_TYPE>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:DOCUMENTTYPE"/>
        </ns1:DOCUMENT_TYPE>
        <ns1:INVOICE_TYPE>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:INVOICETYPE"/>
        </ns1:INVOICE_TYPE>
        <ns1:IMAGE_URL>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:IMAGEURL"/>
        </ns1:IMAGE_URL>
        <ns1:ORG_ID>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:ORGID"/>
        </ns1:ORG_ID>
        <ns1:INVOICE_NUMBER>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:INVOICENUMBER"/>
        </ns1:INVOICE_NUMBER>
        <ns1:SITE_NAME>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:SITENAME"/>
        </ns1:SITE_NAME>
        <ns1:TAX_REG_NUMBER>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:TAXREGISTRATIONNUMBER"/>
        </ns1:TAX_REG_NUMBER>
        <ns1:INVOICE_TOT_AMOUNT>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:INVOICETOTALAMOUNT"/>
        </ns1:INVOICE_TOT_AMOUNT>
        <ns1:CURRENCY_CODE>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:CURRENCYCODE"/>
        </ns1:CURRENCY_CODE>
        <ns1:CERTIFIER_NAME>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:CERTIFIERNAME"/>
        </ns1:CERTIFIER_NAME>
        <ns1:EMPLOYEE_NUMBER>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:EMPLOYEENO"/>
        </ns1:EMPLOYEE_NUMBER>
        <ns1:CERTIFIER_EMAIL_ADD>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:CERTIFIEREMAILADD"/>
        </ns1:CERTIFIER_EMAIL_ADD>
        <ns1:INVALID_REASON>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:INVALIDREASON"/>
        </ns1:INVALID_REASON>
        <ns1:INVALID_CODE>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:INVALIDCODE"/>
        </ns1:INVALID_CODE>
        <ns1:PO_TYPE>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:POTYPE"/>
        </ns1:PO_TYPE>
        <ns1:PRIORITY>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:PRIORITY"/>
        </ns1:PRIORITY>
        <ns1:STATUS>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:STATUS"/>
        </ns1:STATUS>
        <ns1:CERTIFIER_REJ_REASON>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:REJECTIONREASON"/>
        </ns1:CERTIFIER_REJ_REASON>
        <ns1:CERTIFIER_REJ_COMMENTS>
          <xsl:value-of select="/db:OutputParameters/db:P_INVOICE_IN/db:CERTIFIERCOMMENTS"/>
        </ns1:CERTIFIER_REJ_COMMENTS>
      </ns1:FetchUpdateHeader>
      <ns1:FetchUpdatelineItems>
        <xsl:for-each select="/db:OutputParameters/db:P_INV_LINE/db:P_INV_LINE_ITEM">
          <ns1:lineItem>
            <ns1:INVOICE_ID>
              <xsl:value-of select="$ApproveStatusPDO/ns0:ApprovalStatusData/ns0:ApprovalStatusInfo/ns0:InvoiceID"/>
            </ns1:INVOICE_ID>
            <ns1:LINE_NUMBER>
              <xsl:value-of select="db:LINENO"/>
            </ns1:LINE_NUMBER>
            <ns1:LINE_TYPE>
              <xsl:value-of select="db:LINETYPE"/>
            </ns1:LINE_TYPE>
            <ns1:LINE_PO_NUM>
              <xsl:value-of select="db:LINEPONUMBER"/>
            </ns1:LINE_PO_NUM>
            <ns1:PO_LINE_NUM>
              <xsl:value-of select="db:POLINENUMBER"/>
            </ns1:PO_LINE_NUM>
            <ns1:LINE_DESCRIPTION>
              <xsl:value-of select="db:LINEDESCRIPTION"/>
            </ns1:LINE_DESCRIPTION>
            <ns1:QUANTITY>
              <xsl:value-of select="db:QUANTITY"/>
            </ns1:QUANTITY>
            <ns1:UOM>
              <xsl:value-of select="db:UOM"/>
            </ns1:UOM>
            <ns1:UNIT_PRICE>
              <xsl:value-of select="db:UNITPRICE"/>
            </ns1:UNIT_PRICE>
            <ns1:LINE_TOTAL_AMOUNT>
              <xsl:value-of select="db:LINETOTALAMOUNT"/>
            </ns1:LINE_TOTAL_AMOUNT>
            <ns1:TAX_RATE>
              <xsl:value-of select="db:TAXRATE"/>
            </ns1:TAX_RATE>
            <ns1:TAX_RATE_CODE>
              <xsl:value-of select="db:TAXRATECODE"/>
            </ns1:TAX_RATE_CODE>
            <ns1:PROJECT_NO>
              <xsl:value-of select="db:PROJECTNO"/>
            </ns1:PROJECT_NO>
            <ns1:TASK_NO>
              <xsl:value-of select="db:TASKNO"/>
            </ns1:TASK_NO>
            <ns1:EXPINDITURE_ORG>
              <xsl:value-of select="db:EXPENDITUREORG"/>
            </ns1:EXPINDITURE_ORG>
            <ns1:EXPENDITURE_DATE>
              <xsl:value-of select="db:EXPENDITUREDATE"/>
            </ns1:EXPENDITURE_DATE>
            <ns1:GL_NO>
              <xsl:value-of select="db:GLNO"/>
            </ns1:GL_NO>
          </ns1:lineItem>
        </xsl:for-each>
      </ns1:FetchUpdatelineItems>
    </ns1:FetchUpdateData>
  </xsl:template>
</xsl:stylesheet>