
package ap.qantas.com.eQApprovalDetailsService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "approverDetails_ptt", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/TesteQRule/BusinessRulePrj/approverDetails")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ApproverDetailsPtt {


    /**
     * 
     * @param inputParameters
     * @return
     *     returns ap.qantas.com.eQApprovalDetailsService.OutputParameters
     */
    @WebMethod(action = "approverDetails")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/approverDetails", partName = "OutputParameters")
    public OutputParameters approverDetails(
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/approverDetails", partName = "InputParameters")
        InputParameters inputParameters);

}
