package ap.quantas.com.holdReleaseWebService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

//@WebService(wsdlLocation="http://eqsit-ap:16035/integration/services/TaskService/TaskServicePort?WSDL",
//@WebService(wsdlLocation="http://eqdev-soa:16015/integration/services/TaskService/TaskServicePort?WSDL",
@WebService(wsdlLocation="http://eqsoa.qantas.com.au/integration/services/TaskService/TaskServicePort?WSDL",
  targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
  name="TaskService")
@XmlSeeAlso(
  { ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.metadata.routingslip.model.ObjectFactory.class, ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.ObjectFactory.class, ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.ObjectFactory.class, ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.common.model.ObjectFactory.class, ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.common.tsc.model.ObjectFactory.class, ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.evidence.model.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface TaskService
{
  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/initiateTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/initiateTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/initiateTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/initiateTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="initiateTaskResponse")
  public ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskServiceContextTaskBaseType initiateTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="initiateTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.InitiateTaskType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reinitiateTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reinitiateTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reinitiateTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reinitiateTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="reinitiateTaskResponse")
  public ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskServiceContextTaskBaseType reinitiateTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="reinitiateTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.InitiateTaskType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/overrideRoutingSlipInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/overrideRoutingSlip/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/overrideRoutingSlip/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/overrideRoutingSlipOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task overrideRoutingSlip(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="overrideRoutingSlip")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.OverrideRoutingSlipType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/skipCurrentAssignmentInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/skipCurrentAssignment/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/skipCurrentAssignment/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/skipCurrentAssignmentOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task skipCurrentAssignment(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="skipCurrentAssignment")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskServiceContextTaskBaseType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task updateTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="updateTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskServiceContextTaskBaseType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/mergeAndUpdateTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/mergeAndUpdateTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/mergeAndUpdateTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/mergeAndUpdateTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task mergeAndUpdateTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="mergeAndUpdateTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskServiceContextTaskBaseType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/submitInfoForTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/submitInfoForTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/submitInfoForTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/submitInfoForTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task submitInfoForTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="submitInfoForTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskServiceContextTaskBaseType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/getUsersToRequestInfoForTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/getUsersToRequestInfoForTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/getUsersToRequestInfoForTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/getUsersToRequestInfoForTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="listOfUserIds")
  public ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.ListOfUserIdsType getUsersToRequestInfoForTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="getUsersToRequestInfoForTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskServiceContextTaskTaskIdBaseType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/getFutureParticipantsInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/getFutureParticipants/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/getFutureParticipants/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/getFutureParticipantsOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/routingSlip",
    partName="payload", name="routingSlip")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.metadata.routingslip.model.RoutingSlip getFutureParticipants(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="getFutureParticipants")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskServiceContextTaskTaskIdBaseType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/getApproversInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/getApprovers/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/getApprovers/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/getApproversOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="listOfUserIds")
  public ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.ListOfUserIdsType getApprovers(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="getApprovers")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskServiceContextTaskTaskIdBaseType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/escalateTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/escalateTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/escalateTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/escalateTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task escalateTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="escalateTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskServiceContextTaskTaskIdBaseType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/escalateTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/escalateTasks/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/escalateTasks/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/escalateTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="bulkOperationOutput")
  public boolean escalateTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="escalateTasks")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskIdsType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/withdrawTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/withdrawTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/withdrawTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/withdrawTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task withdrawTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="withdrawTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskServiceContextTaskTaskIdBaseType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/withdrawTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/withdrawTasks/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/withdrawTasks/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/withdrawTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="bulkOperationOutput")
  public boolean withdrawTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="withdrawTasks")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskIdsType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/suspendTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/suspendTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/suspendTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/suspendTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task suspendTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="suspendTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskServiceContextTaskTaskIdBaseType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/suspendTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/suspendTasks/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/suspendTasks/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/suspendTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="bulkOperationOutput")
  public boolean suspendTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="suspendTasks")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskIdsType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/resumeTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/resumeTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/resumeTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/resumeTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task resumeTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="resumeTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskServiceContextTaskTaskIdBaseType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/resumeTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/resumeTasks/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/resumeTasks/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/resumeTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="bulkOperationOutput")
  public boolean resumeTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="resumeTasks")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskIdsType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/acquireTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/acquireTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/acquireTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/acquireTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task acquireTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="acquireTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskServiceContextTaskTaskIdBaseType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/acquireTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/acquireTasks/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/acquireTasks/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/acquireTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="bulkOperationOutput")
  public boolean acquireTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="acquireTasks")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskIdsType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/releaseTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/releaseTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/releaseTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/releaseTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task releaseTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="releaseTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskServiceContextTaskTaskIdBaseType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/releaseTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/releaseTasks/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/releaseTasks/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/releaseTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="bulkOperationOutput")
  public boolean releaseTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="releaseTasks")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskIdsType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reassignTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reassignTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reassignTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reassignTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task reassignTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="reassignTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.ReassignTaskType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reassignTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reassignTasks/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reassignTasks/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reassignTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="bulkOperationOutput")
  public boolean reassignTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="reassignTasks")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.ReassignTasksType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/routeTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/routeTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/routeTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/routeTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task routeTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="routeTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.RouteTaskType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/pushBackTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/pushBackTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/pushBackTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/pushBackTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task pushBackTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="pushBackTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskServiceContextTaskTaskIdBaseType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/delegateTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/delegateTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/delegateTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/delegateTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task delegateTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="delegateTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.DelegateTaskType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/delegateTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/delegateTasks/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/delegateTasks/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/delegateTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="bulkOperationOutput")
  public boolean delegateTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="delegateTasks")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.DelegateTasksType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/errorTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/errorTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/errorTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/errorTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task errorTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="errorTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskServiceContextTaskTaskIdBaseType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addCommentInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addComment/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addComment/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addCommentOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task addComment(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="addComment")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.AddCommentType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addCommentToTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addCommentToTasks/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addCommentToTasks/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addCommentToTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="bulkOperationOutput")
  public boolean addCommentToTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="addCommentToTasks")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.AddCommentToTasks payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addAttachmentInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addAttachment/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addAttachment/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addAttachmentOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task addAttachment(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="addAttachment")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.AddAttachmentType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/removeAttachmentInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/removeAttachment/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/removeAttachment/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/removeAttachmentOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task removeAttachment(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="removeAttachment")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.RemoveAttachmentType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addDocumentInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addDocument/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addDocument/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addDocumentOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task addDocument(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="addDocument")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.AddDocumentType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/removeDocumentInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/removeDocument/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/removeDocument/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/removeDocumentOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task removeDocument(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="removeDocument")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.RemoveDocumentType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/renewTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/renewTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/renewTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/renewTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task renewTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="renewTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.RenewTaskType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateTaskOutcomeInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateTaskOutcome/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateTaskOutcome/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateTaskOutcomeOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task updateTaskOutcome(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="updateTaskOutcome")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.UpdateTaskOutcomeType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateOutcomeOfTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateOutcomeOfTasks/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateOutcomeOfTasks/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateOutcomeOfTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="bulkOperationOutput")
  public boolean updateOutcomeOfTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="updateOutcomeOfTasks")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.UpdateOutcomeOfTasks payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateTaskOutcomeAndRouteInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateTaskOutcomeAndRoute/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateTaskOutcomeAndRoute/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateTaskOutcomeAndRouteOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task updateTaskOutcomeAndRoute(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="updateTaskOutcomeAndRoute")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.UpdateTaskOutcomeAndRouteType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/requestInfoForTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/requestInfoForTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/requestInfoForTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/requestInfoForTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task requestInfoForTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="requestInfoForTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.RequestInfoForTaskType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/requestInfoForTaskWithReapprovalInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/requestInfoForTaskWithReapproval/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/requestInfoForTaskWithReapproval/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/requestInfoForTaskWithReapprovalOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task requestInfoForTaskWithReapproval(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="requestInfoForTaskWithReapproval")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.RequestInfoForTaskType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/createToDoTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/createToDoTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/createToDoTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/createToDoTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task createToDoTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="createToDoTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.CreateToDoTaskType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/deleteTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/deleteTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/deleteTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/deleteTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task deleteTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="deleteTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskServiceContextTaskTaskIdBaseType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/deleteTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/deleteTasks/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/deleteTasks/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/deleteTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="bulkOperationOutput")
  public boolean deleteTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="deleteTasks")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskIdsType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/purgeTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/purgeTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/purgeTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/purgeTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="purgeTaskOutput")
  public boolean purgeTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="purgeTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskServiceContextTaskTaskIdBaseType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/purgeTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/purgeTasks/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/purgeTasks/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/purgeTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="bulkOperationOutput")
  public boolean purgeTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="purgeTasks")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskIdsType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/setTaskSequenceChangesInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/setTaskSequenceChanges/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/setTaskSequenceChanges/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/setTaskSequenceChangesOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="setTaskSequenceChangesOutput")
  public int setTaskSequenceChanges(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="setTaskSequenceChanges")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.SetTaskSequenceChangesType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/restartRootTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/restartRootTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/restartRootTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/restartRootTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="initiateTaskResponse")
  public ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskServiceContextTaskBaseType restartRootTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="restartRootTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.RestartRootTaskType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/prepareForRestartRootTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/prepareForRestartRootTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/prepareForRestartRootTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/prepareForRestartRootTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task prepareForRestartRootTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="prepareForRestartRootTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.RestartRootTaskType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reevaluateTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reevaluateTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reevaluateTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reevaluateTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="reevaluateTaskOutput")
  public boolean reevaluateTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="reevaluateTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.ReevaluateTaskType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updatePriorityInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updatePriority/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updatePriority/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updatePriorityOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="successResponseOutput")
  public String updatePriority(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="updatePriority")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.PriorityIdsType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updatePriorityOfTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updatePriorityOfTasks/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updatePriorityOfTasks/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updatePriorityOfTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="successResponseOutput")
  public String updatePriorityOfTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="updatePriorityOfTasks")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.PriorityIdsListType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/suspendTimersInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/suspendTimers/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/suspendTimers/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/suspendTimersOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="successResponseOutput")
  public String suspendTimers(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="suspendTimers")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskServiceContextTaskTaskIdBaseType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/resumeTimersInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/resumeTimers/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/resumeTimers/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/resumeTimersOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="successResponseOutput")
  public String resumeTimers(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="resumeTimers")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.TaskServiceContextTaskTaskIdBaseType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/decomposeTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/decomposeTask/Fault/operationErroredFault",
          className=ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/decomposeTask/Fault/staleObjectFault",
          className=ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/decomposeTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public ap.quantas.com.holdReleaseWebService.oracle.bpel.services.workflow.task.model.Task decomposeTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="decomposeTask")
    ap.quantas.com.holdReleaseWebService.oracle.xmlns.bpel.workflow.taskservice.DecomposeTaskType payload)
    throws ap.quantas.com.holdReleaseWebService.WorkflowErrorMessage, ap.quantas.com.holdReleaseWebService.StaleObjectFaultMessage;
}
