
package oracle.imaging;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DocumentContentService", targetNamespace = "http://imaging.oracle/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DocumentContentService {


    /**
     * 
     * @param documentId
     * @return
     *     returns byte[]
     * @throws ImagingException
     */
    @WebMethod
    @WebResult(name = "documentData", targetNamespace = "")
    @RequestWrapper(localName = "retrieve", targetNamespace = "http://imaging.oracle/", className = "oracle.imaging.Retrieve")
    @ResponseWrapper(localName = "retrieveResponse", targetNamespace = "http://imaging.oracle/", className = "oracle.imaging.RetrieveResponse")
    @Action(input = "http://imaging.oracle/DocumentContentService/retrieveRequest", output = "http://imaging.oracle/DocumentContentService/retrieveResponse", fault = {
        @FaultAction(className = ImagingException.class, value = "http://imaging.oracle/DocumentContentService/retrieve/Fault/ImagingException")
    })
    public byte[] retrieve(
        @WebParam(name = "documentId", targetNamespace = "")
        String documentId)
        throws ImagingException
    ;

    /**
     * 
     * @param versionId
     * @param documentId
     * @return
     *     returns byte[]
     * @throws ImagingException
     */
    @WebMethod
    @WebResult(name = "documentData", targetNamespace = "")
    @RequestWrapper(localName = "retrieveVersion", targetNamespace = "http://imaging.oracle/", className = "oracle.imaging.RetrieveVersion")
    @ResponseWrapper(localName = "retrieveVersionResponse", targetNamespace = "http://imaging.oracle/", className = "oracle.imaging.RetrieveVersionResponse")
    @Action(input = "http://imaging.oracle/DocumentContentService/retrieveVersionRequest", output = "http://imaging.oracle/DocumentContentService/retrieveVersionResponse", fault = {
        @FaultAction(className = ImagingException.class, value = "http://imaging.oracle/DocumentContentService/retrieveVersion/Fault/ImagingException")
    })
    public byte[] retrieveVersion(
        @WebParam(name = "documentId", targetNamespace = "")
        String documentId,
        @WebParam(name = "versionId", targetNamespace = "")
        long versionId)
        throws ImagingException
    ;

    /**
     * 
     * @param fileName
     * @param data
     * @return
     *     returns java.lang.String
     * @throws ImagingException
     */
    @WebMethod
    @WebResult(name = "uploadToken", targetNamespace = "")
    @RequestWrapper(localName = "uploadDocument", targetNamespace = "http://imaging.oracle/", className = "oracle.imaging.UploadDocument")
    @ResponseWrapper(localName = "uploadDocumentResponse", targetNamespace = "http://imaging.oracle/", className = "oracle.imaging.UploadDocumentResponse")
    @Action(input = "http://imaging.oracle/DocumentContentService/uploadDocumentRequest", output = "http://imaging.oracle/DocumentContentService/uploadDocumentResponse", fault = {
        @FaultAction(className = ImagingException.class, value = "http://imaging.oracle/DocumentContentService/uploadDocument/Fault/ImagingException")
    })
    public String uploadDocument(
        @WebParam(name = "data", targetNamespace = "")
        byte[] data,
        @WebParam(name = "fileName", targetNamespace = "")
        String fileName)
        throws ImagingException
    ;

    /**
     * 
     * @param options
     * @param documentId
     * @return
     *     returns oracle.imaging.RenderResult
     * @throws ImagingException
     */
    @WebMethod
    @WebResult(name = "renderResult", targetNamespace = "")
    @RequestWrapper(localName = "retrievePage", targetNamespace = "http://imaging.oracle/", className = "oracle.imaging.RetrievePage")
    @ResponseWrapper(localName = "retrievePageResponse", targetNamespace = "http://imaging.oracle/", className = "oracle.imaging.RetrievePageResponse")
    @Action(input = "http://imaging.oracle/DocumentContentService/retrievePageRequest", output = "http://imaging.oracle/DocumentContentService/retrievePageResponse", fault = {
        @FaultAction(className = ImagingException.class, value = "http://imaging.oracle/DocumentContentService/retrievePage/Fault/ImagingException")
    })
    public RenderResult retrievePage(
        @WebParam(name = "documentId", targetNamespace = "")
        String documentId,
        @WebParam(name = "options", targetNamespace = "")
        RenderOptions options)
        throws ImagingException
    ;

    /**
     * 
     * @param pages
     * @param withAnnotations
     * @param outputType
     * @param documentId
     * @param preserveColor
     * @return
     *     returns oracle.imaging.Rendition
     * @throws ImagingException
     */
    @WebMethod
    @WebResult(name = "rendition", targetNamespace = "")
    @RequestWrapper(localName = "retrieveRendition", targetNamespace = "http://imaging.oracle/", className = "oracle.imaging.RetrieveRendition")
    @ResponseWrapper(localName = "retrieveRenditionResponse", targetNamespace = "http://imaging.oracle/", className = "oracle.imaging.RetrieveRenditionResponse")
    @Action(input = "http://imaging.oracle/DocumentContentService/retrieveRenditionRequest", output = "http://imaging.oracle/DocumentContentService/retrieveRenditionResponse", fault = {
        @FaultAction(className = ImagingException.class, value = "http://imaging.oracle/DocumentContentService/retrieveRendition/Fault/ImagingException")
    })
    public Rendition retrieveRendition(
        @WebParam(name = "documentId", targetNamespace = "")
        String documentId,
        @WebParam(name = "withAnnotations", targetNamespace = "")
        boolean withAnnotations,
        @WebParam(name = "preserveColor", targetNamespace = "")
        boolean preserveColor,
        @WebParam(name = "outputType", targetNamespace = "")
        RenditionOutput outputType,
        @WebParam(name = "pages", targetNamespace = "")
        List<Integer> pages)
        throws ImagingException
    ;

    /**
     * 
     * @param versionId
     * @param pages
     * @param withAnnotations
     * @param outputType
     * @param documentId
     * @param preserveColor
     * @return
     *     returns oracle.imaging.Rendition
     * @throws ImagingException
     */
    @WebMethod
    @WebResult(name = "rendition", targetNamespace = "")
    @RequestWrapper(localName = "retrieveVersionRendition", targetNamespace = "http://imaging.oracle/", className = "oracle.imaging.RetrieveVersionRendition")
    @ResponseWrapper(localName = "retrieveVersionRenditionResponse", targetNamespace = "http://imaging.oracle/", className = "oracle.imaging.RetrieveVersionRenditionResponse")
    @Action(input = "http://imaging.oracle/DocumentContentService/retrieveVersionRenditionRequest", output = "http://imaging.oracle/DocumentContentService/retrieveVersionRenditionResponse", fault = {
        @FaultAction(className = ImagingException.class, value = "http://imaging.oracle/DocumentContentService/retrieveVersionRendition/Fault/ImagingException")
    })
    public Rendition retrieveVersionRendition(
        @WebParam(name = "documentId", targetNamespace = "")
        String documentId,
        @WebParam(name = "versionId", targetNamespace = "")
        long versionId,
        @WebParam(name = "withAnnotations", targetNamespace = "")
        boolean withAnnotations,
        @WebParam(name = "preserveColor", targetNamespace = "")
        boolean preserveColor,
        @WebParam(name = "outputType", targetNamespace = "")
        RenditionOutput outputType,
        @WebParam(name = "pages", targetNamespace = "")
        List<Integer> pages)
        throws ImagingException
    ;

    /**
     * 
     * @param versionId
     * @param options
     * @param documentId
     * @return
     *     returns oracle.imaging.RenderResult
     * @throws ImagingException
     */
    @WebMethod
    @WebResult(name = "renderResult", targetNamespace = "")
    @RequestWrapper(localName = "retrieveVersionPage", targetNamespace = "http://imaging.oracle/", className = "oracle.imaging.RetrieveVersionPage")
    @ResponseWrapper(localName = "retrieveVersionPageResponse", targetNamespace = "http://imaging.oracle/", className = "oracle.imaging.RetrieveVersionPageResponse")
    @Action(input = "http://imaging.oracle/DocumentContentService/retrieveVersionPageRequest", output = "http://imaging.oracle/DocumentContentService/retrieveVersionPageResponse", fault = {
        @FaultAction(className = ImagingException.class, value = "http://imaging.oracle/DocumentContentService/retrieveVersionPage/Fault/ImagingException")
    })
    public RenderResult retrieveVersionPage(
        @WebParam(name = "documentId", targetNamespace = "")
        String documentId,
        @WebParam(name = "versionId", targetNamespace = "")
        long versionId,
        @WebParam(name = "options", targetNamespace = "")
        RenderOptions options)
        throws ImagingException
    ;

}
