
package ap.quantas.com.ebs_inv_process_new.js;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "JSEQ_INV_IMG_PROCESS_ptt-bindingQSService", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/WCC_CODES1/JS_INV_IMG_PROCESS/JSEQ_INV_IMG_PROCESS", wsdlLocation = "http://eqosb.qantas.com.au/QFEQ_AP_INV_IMG_PROCESS/Proxy_Service/JSEQ_INV_IMG_PROCESS_PS?wsdl")
public class JSEQINVIMGPROCESSPttBindingQSService
    extends Service
{

    private final static URL JSEQINVIMGPROCESSPTTBINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException JSEQINVIMGPROCESSPTTBINDINGQSSERVICE_EXCEPTION;
    private final static QName JSEQINVIMGPROCESSPTTBINDINGQSSERVICE_QNAME = new QName("http://xmlns.oracle.com/pcbpel/adapter/db/WCC_CODES1/JS_INV_IMG_PROCESS/JSEQ_INV_IMG_PROCESS", "JSEQ_INV_IMG_PROCESS_ptt-bindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://eqosb.qantas.com.au/QFEQ_AP_INV_IMG_PROCESS/Proxy_Service/JSEQ_INV_IMG_PROCESS_PS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
            } catch(Exception e1){
                System.out.println(e1);
                e1.printStackTrace();
            }
        JSEQINVIMGPROCESSPTTBINDINGQSSERVICE_WSDL_LOCATION = url;
        JSEQINVIMGPROCESSPTTBINDINGQSSERVICE_EXCEPTION = e;
    }

    public JSEQINVIMGPROCESSPttBindingQSService() {
        super(__getWsdlLocation(), JSEQINVIMGPROCESSPTTBINDINGQSSERVICE_QNAME);
    }

    public JSEQINVIMGPROCESSPttBindingQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JSEQINVIMGPROCESSPTTBINDINGQSSERVICE_QNAME, features);
    }

    public JSEQINVIMGPROCESSPttBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, JSEQINVIMGPROCESSPTTBINDINGQSSERVICE_QNAME);
    }

    public JSEQINVIMGPROCESSPttBindingQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JSEQINVIMGPROCESSPTTBINDINGQSSERVICE_QNAME, features);
    }

    public JSEQINVIMGPROCESSPttBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JSEQINVIMGPROCESSPttBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns JSEQINVIMGPROCESSPtt
     */
    @WebEndpoint(name = "JSEQ_INV_IMG_PROCESS_ptt-bindingQSPort")
    public JSEQINVIMGPROCESSPtt getJSEQINVIMGPROCESSPttBindingQSPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/pcbpel/adapter/db/WCC_CODES1/JS_INV_IMG_PROCESS/JSEQ_INV_IMG_PROCESS", "JSEQ_INV_IMG_PROCESS_ptt-bindingQSPort"), JSEQINVIMGPROCESSPtt.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JSEQINVIMGPROCESSPtt
     */
    @WebEndpoint(name = "JSEQ_INV_IMG_PROCESS_ptt-bindingQSPort")
    public JSEQINVIMGPROCESSPtt getJSEQINVIMGPROCESSPttBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/pcbpel/adapter/db/WCC_CODES1/JS_INV_IMG_PROCESS/JSEQ_INV_IMG_PROCESS", "JSEQ_INV_IMG_PROCESS_ptt-bindingQSPort"), JSEQINVIMGPROCESSPtt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JSEQINVIMGPROCESSPTTBINDINGQSSERVICE_EXCEPTION!= null) {
            throw JSEQINVIMGPROCESSPTTBINDINGQSSERVICE_EXCEPTION;
        }
        return JSEQINVIMGPROCESSPTTBINDINGQSSERVICE_WSDL_LOCATION;
    }

}
