
package ap.quantas.com.ebs_inv_process_new.js;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JSEQ_INV_IMG_PROCESS_ptt", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/WCC_CODES1/JS_INV_IMG_PROCESS/JSEQ_INV_IMG_PROCESS")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JSEQINVIMGPROCESSPtt {


    /**
     * 
     * @param inputParameters
     * @return
     *     returns ap.quantas.com.ebs_inv_process_new.js.OutputParameters
     */
    @WebMethod(operationName = "JSEQ_INV_IMG_PROCESS", action = "JSEQ_INV_IMG_PROCESS")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/JSEQ_INV_IMG_PROCESS", partName = "OutputParameters")
    public OutputParameters jseqINVIMGPROCESS(
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/JSEQ_INV_IMG_PROCESS", partName = "InputParameters")
        InputParameters inputParameters);

}
