package qantas.com.au.overseas.model.client;

import oracle.jbo.client.remote.ApplicationModuleImpl;

import qantas.com.au.overseas.model.common.EQfiles_APModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 25 15:58:58 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EQfiles_APModuleClient extends ApplicationModuleImpl implements EQfiles_APModule {
    /**
     * This is the default constructor (do not remove).
     */
    public EQfiles_APModuleClient() {
    }


    public void saveTemplate(String userId, String supName, String suppNum,
                             String siteId, String operatingUnit,
                             String taxReg, String invoiceType, String docType,
                             String templateName) {
        Object _ret =
            this.riInvokeExportedMethod(this,"saveTemplate",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {userId, supName, suppNum, siteId, operatingUnit, taxReg, invoiceType, docType, templateName});
        return;
    }


    public void saveTemplate(String userId, String supName, String suppNum,
                             String siteId, String operatingUnit,
                             String taxReg, String invoiceType, String docType,
                             String templateName, String orgId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"saveTemplate",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {userId, supName, suppNum, siteId, operatingUnit, taxReg, invoiceType, docType, templateName, orgId});
        return;
    }

    public void invoiceHeaderLinedataload() {
        Object _ret =
            this.riInvokeExportedMethod(this,"invoiceHeaderLinedataload",null,null);
        return;
    }

    public void addLineItemRow(String invoiceId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"addLineItemRow",new String [] {"java.lang.String"},new Object[] {invoiceId});
        return;
    }

    public void saveAllFormDetails(String invoiceId, String siteId,
                                   String supName, String currency,
                                   String employeeNo) {
        Object _ret =
            this.riInvokeExportedMethod(this,"saveAllFormDetails",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {invoiceId, siteId, supName, currency, employeeNo});
        return;
    }

    public void onAddTemplateRow(String userId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"onAddTemplateRow",new String [] {"java.lang.String"},new Object[] {userId});
        return;
    }

    public void onAddTemplateRow_new(String userId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"onAddTemplateRow_new",new String [] {"java.lang.String"},new Object[] {userId});
        return;
    }

    public void saveTemplate(String userId, String supName, String suppNum,
                             String siteId, String operatingUnit,
                             String taxReg, String invoiceType, String docType,
                             String templateName, String orgId,
                             String siteName) {
        Object _ret =
            this.riInvokeExportedMethod(this,"saveTemplate",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {userId, supName, suppNum, siteId, operatingUnit, taxReg, invoiceType, docType, templateName, orgId, siteName});
        return;
    }
}
