package ap.quantas.com.ebs_inv_process_new.db;

import ap.quantas.com.ebs_inv_process_new.sp.APPSINVOICEHEADERREC;
import ap.quantas.com.ebs_inv_process_new.sp.InputParameters;
import ap.quantas.com.ebs_inv_process_new.sp.ObjectFactory;

import ap.quantas.com.ebs_inv_process_new.sp.OutputParameters;

import java.io.StringWriter;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

public class QFEQ_AP_INV_IMG_PROCESS_pttBindingQSPortClient
{
  @WebServiceRef
  private static QFEQ_AP_INV_IMG_PROCESS_pttBindingQSService qFEQ_AP_INV_IMG_PROCESS_pttBindingQSService;

  public static void main(String [] args) throws JAXBException {
      QFEQ_AP_INV_IMG_PROCESS_pttBindingQSService qFEQ_AP_INV_IMG_PROCESS_pttBindingQSService = new QFEQ_AP_INV_IMG_PROCESS_pttBindingQSService();
                  qFEQ_AP_INV_IMG_PROCESS_pttBindingQSService = new QFEQ_AP_INV_IMG_PROCESS_pttBindingQSService();
                  QFEQ_AP_INV_IMG_PROCESS_ptt qFEQ_AP_INV_IMG_PROCESS_ptt = qFEQ_AP_INV_IMG_PROCESS_pttBindingQSService.getQFEQ_AP_INV_IMG_PROCESS_pttBindingQSPort();
                  
                  ObjectFactory objectFactory = new ObjectFactory();
                  InputParameters input_params = objectFactory.createInputParameters();

                  //input_params.setPCALLEDFROM(objectFactory.createInputParametersPCALLEDFROM("WFR")); // as communicated from BPM's end
                  
                  
                  APPSINVOICEHEADERREC appsinvoiceheaderrec = objectFactory.createAPPSINVOICEHEADERREC();
                                    //appsinvoiceheaderrec.setALTERNATEAPPROVEREMPLOYEENO(objectFactory.createAPPSINVOICEHEADERRECALTERNATEAPPROVEREMPLOYEENO(""));
                                    
                                    appsinvoiceheaderrec.setDOCUMENTTYPE(objectFactory.createAPPSINVOICEHEADERRECDOCUMENTTYPE(""));
                                    appsinvoiceheaderrec.setINVOICETYPE(objectFactory.createAPPSINVOICEHEADERRECINVOICETYPE("" ));
                                    appsinvoiceheaderrec.setORGID(objectFactory.createAPPSINVOICEHEADERRECORGID(null));
                                    appsinvoiceheaderrec.setINVOICENUMBER(objectFactory.createAPPSINVOICEHEADERRECINVOICENUMBER( "123" ));
                                    appsinvoiceheaderrec.setINVOICEDATE(null );
                                  
                                    
                                   
                                    input_params.setPINVOICEIN(objectFactory.createInputParametersPINVOICEIN(appsinvoiceheaderrec));
                                    
            StringWriter writer = new StringWriter();
                                            JAXBContext context = JAXBContext.newInstance(APPSINVOICEHEADERREC.class);
                                Marshaller m = context.createMarshaller();              
                                m.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);
                                m.marshal(
                                    input_params.getPINVOICEIN(), 
                                    writer
                                );
                                            
                                            
            System.out.println("PAyload :: "+writer.toString());
                            
                                    
                                    
            OutputParameters outputparams = qFEQ_AP_INV_IMG_PROCESS_ptt.qfeqAPINVIMGPROCESS(input_params);;
            //System.out.println("Get supplier name from ebs package :: "+outputparams.getPINVOICEIN().getValue().getINVOICENUMBER().getValue());
            System.out.println("value :: "+outputparams.getOUTRESULT().getValue());
            System.out.println("value1 :: "+outputparams.getOUTRESULT().getValue().getOUTRESULTITEM().get(0).getERRORMESSAGE().getValue());
  }
}
