package ap.quantas.com.ebs_inv_process_new.db;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://eqosb.qantas.com.au/QFEQ_AP_INV_IMG_PROCESS/Proxy_Service/QFEQ_AP_INV_IMG_PROCESS_PS?wsdl",
  targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/QFEQ_AP_INV_IMG_PROCESS_TEST-EBS/QFEQ_AP_INV_IMG_PROCESS/QFEQ_AP_INV_IMG_PROCESS",
  name="QFEQ_AP_INV_IMG_PROCESS_ptt")
@XmlSeeAlso(
  { ap.quantas.com.ebs_inv_process_new.sp.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface QFEQ_AP_INV_IMG_PROCESS_ptt
{
  @WebMethod(operationName="QFEQ_AP_INV_IMG_PROCESS", action="QFEQ_AP_INV_IMG_PROCESS")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="QFEQ_AP_INV_IMG_PROCESS", output="http://xmlns.oracle.com/pcbpel/adapter/db/QFEQ_AP_INV_IMG_PROCESS_TEST-EBS/QFEQ_AP_INV_IMG_PROCESS/QFEQ_AP_INV_IMG_PROCESS/QFEQ_AP_INV_IMG_PROCESS_ptt/QFEQ_AP_INV_IMG_PROCESSResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/QFEQ_AP_INV_IMG_PROCESS",
    partName="OutputParameters", name="OutputParameters")
  public ap.quantas.com.ebs_inv_process_new.sp.OutputParameters qfeqAPINVIMGPROCESS(@WebParam(targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/QFEQ_AP_INV_IMG_PROCESS",
      partName="InputParameters", name="InputParameters")
    ap.quantas.com.ebs_inv_process_new.sp.InputParameters InputParameters);
}
