package ap.quantas.com.ebs_inv_process_new.db;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.el.ELContext;
import javax.el.ExpressionFactory;
import javax.el.ValueExpression;

import javax.faces.application.Application;
import javax.faces.context.FacesContext;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="http://eqosb.qantas.com.au/QFEQ_AP_INV_IMG_PROCESS/Proxy_Service/QFEQ_AP_INV_IMG_PROCESS_PS?wsdl",
  targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/QFEQ_AP_INV_IMG_PROCESS_TEST-EBS/QFEQ_AP_INV_IMG_PROCESS/QFEQ_AP_INV_IMG_PROCESS",
  name="QFEQ_AP_INV_IMG_PROCESS_ptt-bindingQSService")
public class QFEQ_AP_INV_IMG_PROCESS_pttBindingQSService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
    public static FacesContext getFacesContext() {
        return FacesContext.getCurrentInstance();
    }

    public static Object resolveExpression(String expression) {
        FacesContext facesContext = getFacesContext();
        Application app = facesContext.getApplication();
        ExpressionFactory elFactory = app.getExpressionFactory();
        ELContext elContext = facesContext.getELContext();
        ValueExpression valueExp =
            elFactory.createValueExpression(elContext, expression,
                                            Object.class);
        return valueExp.getValue(elContext);
    }
  static
  {
    try
    {
      logger = Logger.getLogger("ap.quantas.com.ebs_inv_process_new.db.QFEQ_AP_INV_IMG_PROCESS_pttBindingQSService");
      URL baseUrl =
        QFEQ_AP_INV_IMG_PROCESS_pttBindingQSService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            QFEQ_AP_INV_IMG_PROCESS_pttBindingQSService.class.getResource(resolveExpression("#{backing_ap_overseasPage.propertyLoader.properties['EBS_VALIDATION_SERVICE']}").toString());
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, resolveExpression("#{backing_ap_overseasPage.propertyLoader.properties['EBS_VALIDATION_SERVICE']}").toString());
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, resolveExpression("#{backing_ap_overseasPage.propertyLoader.properties['EBS_VALIDATION_SERVICE']}").toString());
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
        "Failed to create wsdlLocationURL using "+resolveExpression("#{backing_ap_overseasPage.propertyLoader.properties['EBS_VALIDATION_SERVICE']}").toString(),
          e);
    }
    catch(Exception e1){
        System.out.println(e1);
        e1.printStackTrace();
    }
  }

  public QFEQ_AP_INV_IMG_PROCESS_pttBindingQSService()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/pcbpel/adapter/db/QFEQ_AP_INV_IMG_PROCESS_TEST-EBS/QFEQ_AP_INV_IMG_PROCESS/QFEQ_AP_INV_IMG_PROCESS",
                    "QFEQ_AP_INV_IMG_PROCESS_ptt-bindingQSService"));
  }

  public QFEQ_AP_INV_IMG_PROCESS_pttBindingQSService(URL wsdlLocation,
                                                     QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="QFEQ_AP_INV_IMG_PROCESS_ptt-bindingQSPort")
  public ap.quantas.com.ebs_inv_process_new.db.QFEQ_AP_INV_IMG_PROCESS_ptt getQFEQ_AP_INV_IMG_PROCESS_pttBindingQSPort()
  {
    return (ap.quantas.com.ebs_inv_process_new.db.QFEQ_AP_INV_IMG_PROCESS_ptt) super.getPort(new QName("http://xmlns.oracle.com/pcbpel/adapter/db/QFEQ_AP_INV_IMG_PROCESS_TEST-EBS/QFEQ_AP_INV_IMG_PROCESS/QFEQ_AP_INV_IMG_PROCESS",
                                                                                                       "QFEQ_AP_INV_IMG_PROCESS_ptt-bindingQSPort"),
                                                                                             ap.quantas.com.ebs_inv_process_new.db.QFEQ_AP_INV_IMG_PROCESS_ptt.class);
  }

  @WebEndpoint(name="QFEQ_AP_INV_IMG_PROCESS_ptt-bindingQSPort")
  public ap.quantas.com.ebs_inv_process_new.db.QFEQ_AP_INV_IMG_PROCESS_ptt getQFEQ_AP_INV_IMG_PROCESS_pttBindingQSPort(WebServiceFeature... features)
  {
    return (ap.quantas.com.ebs_inv_process_new.db.QFEQ_AP_INV_IMG_PROCESS_ptt) super.getPort(new QName("http://xmlns.oracle.com/pcbpel/adapter/db/QFEQ_AP_INV_IMG_PROCESS_TEST-EBS/QFEQ_AP_INV_IMG_PROCESS/QFEQ_AP_INV_IMG_PROCESS",
                                                                                                       "QFEQ_AP_INV_IMG_PROCESS_ptt-bindingQSPort"),
                                                                                             ap.quantas.com.ebs_inv_process_new.db.QFEQ_AP_INV_IMG_PROCESS_ptt.class,
                                                                                             features);
  }
}
