
package ap.quantas.com.imaging.documentSearchService;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SearchService", targetNamespace = "http://imaging.oracle/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SearchService {


    /**
     * 
     * @param searchNameId
     * @param sectionSet
     * @return
     *     returns ap.quantas.com.imaging.documentSearchService.Search
     * @throws ImagingException
     */
    @WebMethod
    @WebResult(name = "search", targetNamespace = "http://imaging.oracle/")
    @RequestWrapper(localName = "getSearch", targetNamespace = "http://imaging.oracle/", className = "ap.quantas.com.imaging.documentSearchService.GetSearch")
    @ResponseWrapper(localName = "getSearchResponse", targetNamespace = "http://imaging.oracle/", className = "ap.quantas.com.imaging.documentSearchService.GetSearchResponse")
    public Search getSearch(
        @WebParam(name = "searchNameId", targetNamespace = "")
        NameId searchNameId,
        @WebParam(name = "sectionSet", targetNamespace = "http://imaging.oracle/")
        SectionSet sectionSet)
        throws ImagingException
    ;

    /**
     * 
     * @param searchNameId
     * @param searchArguments
     * @return
     *     returns ap.quantas.com.imaging.documentSearchService.SearchResultSet
     * @throws ImagingException
     */
    @WebMethod
    @WebResult(name = "searchResults", targetNamespace = "")
    @RequestWrapper(localName = "executeSavedSearch", targetNamespace = "http://imaging.oracle/", className = "ap.quantas.com.imaging.documentSearchService.ExecuteSavedSearch")
    @ResponseWrapper(localName = "executeSavedSearchResponse", targetNamespace = "http://imaging.oracle/", className = "ap.quantas.com.imaging.documentSearchService.ExecuteSavedSearchResponse")
    public SearchResultSet executeSavedSearch(
        @WebParam(name = "searchNameId", targetNamespace = "")
        NameId searchNameId,
        @WebParam(name = "searchArguments", targetNamespace = "")
        List<SearchParameter> searchArguments)
        throws ImagingException
    ;

    /**
     * 
     * @param searchNameId
     * @return
     *     returns ap.quantas.com.imaging.documentSearchService.SearchParameters
     * @throws ImagingException
     */
    @WebMethod
    @WebResult(name = "searchParameters", targetNamespace = "http://imaging.oracle/")
    @RequestWrapper(localName = "getSearchParameters", targetNamespace = "http://imaging.oracle/", className = "ap.quantas.com.imaging.documentSearchService.GetSearchParameters")
    @ResponseWrapper(localName = "getSearchParametersResponse", targetNamespace = "http://imaging.oracle/", className = "ap.quantas.com.imaging.documentSearchService.GetSearchParametersResponse")
    public SearchParameters getSearchParameters(
        @WebParam(name = "searchNameId", targetNamespace = "")
        NameId searchNameId)
        throws ImagingException
    ;

    /**
     * 
     * @param search
     * @param searchArguments
     * @return
     *     returns ap.quantas.com.imaging.documentSearchService.SearchResultSet
     * @throws ImagingException
     */
    @WebMethod
    @WebResult(name = "searchResults", targetNamespace = "")
    @RequestWrapper(localName = "executeSearch", targetNamespace = "http://imaging.oracle/", className = "ap.quantas.com.imaging.documentSearchService.ExecuteSearch")
    @ResponseWrapper(localName = "executeSearchResponse", targetNamespace = "http://imaging.oracle/", className = "ap.quantas.com.imaging.documentSearchService.ExecuteSearchResponse")
    public SearchResultSet executeSearch(
        @WebParam(name = "search", targetNamespace = "http://imaging.oracle/")
        Search search,
        @WebParam(name = "searchArguments", targetNamespace = "")
        List<SearchParameter> searchArguments)
        throws ImagingException
    ;

    /**
     * 
     * @param search
     * @param sectionSet
     * @throws ValidationException
     * @throws ImagingException
     */
    @WebMethod
    @RequestWrapper(localName = "modifySearch", targetNamespace = "http://imaging.oracle/", className = "ap.quantas.com.imaging.documentSearchService.ModifySearch")
    @ResponseWrapper(localName = "modifySearchResponse", targetNamespace = "http://imaging.oracle/", className = "ap.quantas.com.imaging.documentSearchService.ModifySearchResponse")
    public void modifySearch(
        @WebParam(name = "search", targetNamespace = "http://imaging.oracle/")
        Search search,
        @WebParam(name = "sectionSet", targetNamespace = "http://imaging.oracle/")
        SectionSet sectionSet)
        throws ImagingException, ValidationException
    ;

    /**
     * 
     * @param search
     * @return
     *     returns ap.quantas.com.imaging.documentSearchService.NameId
     * @throws ValidationException
     * @throws ImagingException
     */
    @WebMethod
    @WebResult(name = "search", targetNamespace = "")
    @RequestWrapper(localName = "createSearch", targetNamespace = "http://imaging.oracle/", className = "ap.quantas.com.imaging.documentSearchService.CreateSearch")
    @ResponseWrapper(localName = "createSearchResponse", targetNamespace = "http://imaging.oracle/", className = "ap.quantas.com.imaging.documentSearchService.CreateSearchResponse")
    public NameId createSearch(
        @WebParam(name = "search", targetNamespace = "http://imaging.oracle/")
        Search search)
        throws ImagingException, ValidationException
    ;

    /**
     * 
     * @param ability
     * @return
     *     returns java.util.List<ap.quantas.com.imaging.documentSearchService.NameId>
     * @throws ImagingException
     */
    @WebMethod
    @WebResult(name = "searchNameIds", targetNamespace = "")
    @RequestWrapper(localName = "listSearches", targetNamespace = "http://imaging.oracle/", className = "ap.quantas.com.imaging.documentSearchService.ListSearches")
    @ResponseWrapper(localName = "listSearchesResponse", targetNamespace = "http://imaging.oracle/", className = "ap.quantas.com.imaging.documentSearchService.ListSearchesResponse")
    public List<NameId> listSearches(
        @WebParam(name = "ability", targetNamespace = "")
        Ability ability)
        throws ImagingException
    ;

    /**
     * 
     * @param searchNameIds
     * @param sectionSet
     * @return
     *     returns java.util.List<ap.quantas.com.imaging.documentSearchService.Search>
     * @throws ImagingException
     */
    @WebMethod
    @WebResult(name = "searches", targetNamespace = "")
    @RequestWrapper(localName = "getSearches", targetNamespace = "http://imaging.oracle/", className = "ap.quantas.com.imaging.documentSearchService.GetSearches")
    @ResponseWrapper(localName = "getSearchesResponse", targetNamespace = "http://imaging.oracle/", className = "ap.quantas.com.imaging.documentSearchService.GetSearchesResponse")
    public List<Search> getSearches(
        @WebParam(name = "searchNameIds", targetNamespace = "")
        List<NameId> searchNameIds,
        @WebParam(name = "sectionSet", targetNamespace = "http://imaging.oracle/")
        SectionSet sectionSet)
        throws ImagingException
    ;

    /**
     * 
     * @param searchNameId
     * @throws ImagingException
     */
    @WebMethod
    @RequestWrapper(localName = "deleteSearch", targetNamespace = "http://imaging.oracle/", className = "ap.quantas.com.imaging.documentSearchService.DeleteSearch")
    @ResponseWrapper(localName = "deleteSearchResponse", targetNamespace = "http://imaging.oracle/", className = "ap.quantas.com.imaging.documentSearchService.DeleteSearchResponse")
    public void deleteSearch(
        @WebParam(name = "searchNameId", targetNamespace = "")
        NameId searchNameId)
        throws ImagingException
    ;

}
