package model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 14 19:06:34 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HeaderLineVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public HeaderLineVOImpl() {
    }
}
