package model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 14 16:10:15 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class POVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public POVOImpl() {
    }

    /**
     * Returns the variable value for bindPONum.
     * @return variable value for bindPONum
     */
    public String getbindPONum() {
        return (String)ensureVariableManager().getVariableValue("bindPONum");
    }

    /**
     * Sets <code>value</code> for variable bindPONum.
     * @param value value to bind as bindPONum
     */
    public void setbindPONum(String value) {
        ensureVariableManager().setVariableValue("bindPONum", value);
    }


    /**
     * Returns the variable value for bindSiteId.
     * @return variable value for bindSiteId
     */
    public String getbindSiteId() {
        return (String)ensureVariableManager().getVariableValue("bindSiteId");
    }

    /**
     * Sets <code>value</code> for variable bindSiteId.
     * @param value value to bind as bindSiteId
     */
    public void setbindSiteId(String value) {
        ensureVariableManager().setVariableValue("bindSiteId", value);
    }
}
