
package ap.quantas.com.imaging.documentContentService;

import ap.quantas.com.Utility;

import com.bea.security.providers.xacml.entitlement.parser.Users;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
//same wsdl for dev n sit--@WebServiceClient(name = "DocumentContentService", targetNamespace = "http://imaging.oracle/", wsdlLocation = "http://eqdev-capture1.qantas.com.au:16033/imaging/ws/DocumentContentService?wsdl")

@WebServiceClient(name = "DocumentContentService", targetNamespace = "http://imaging.oracle/", wsdlLocation = "http://eqprod-capture1.qantas.com.au:16033/imaging/ws/DocumentContentService?wsdl")
public class DocumentContentService_Service
    extends Service
{

    private final static URL DOCUMENTCONTENTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ap.quantas.com.imaging.documentContentService.DocumentContentService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ap.quantas.com.imaging.documentContentService.DocumentContentService_Service.class.getResource(".");
            
            url = new URL(baseUrl, Utility.resolveExpression("#{ApOperationBean.propertyLoader.properties['IMAGING_DOCUMENT_CONTENT_SERVICE_WSDL']}").toString());
            //url = new URL(baseUrl, "http://eqtest-capture1.qantas.com.au:16033/imaging/ws/DocumentContentService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '"+Utility.resolveExpression("#{ApOperationBean.propertyLoader.properties['IMAGING_DOCUMENT_CONTENT_SERVICE_WSDL']}").toString() +"', retrying as a local file");
            logger.warning(e.getMessage());
        }
        catch (Exception e) {
                    System.out.println(e);
                }
        DOCUMENTCONTENTSERVICE_WSDL_LOCATION = url;
    }

    public DocumentContentService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentContentService_Service() {
        super(DOCUMENTCONTENTSERVICE_WSDL_LOCATION, new QName("http://imaging.oracle/", "DocumentContentService"));
    }

    /**
     * 
     * @return
     *     returns DocumentContentService
     */
    @WebEndpoint(name = "DocumentContentServicePort")
    public DocumentContentService getDocumentContentServicePort() {
        return super.getPort(new QName("http://imaging.oracle/", "DocumentContentServicePort"), DocumentContentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentContentService
     */
    @WebEndpoint(name = "DocumentContentServicePort")
    public DocumentContentService getDocumentContentServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://imaging.oracle/", "DocumentContentServicePort"), DocumentContentService.class, features);
    }

}
