package qantas.integration.util.wsclient;

import java.io.File;

import java.io.FileInputStream;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="http://eqdev-soa.qantas.com.au:16015/IHubFileMgmt/QFEQIFFileLockingServicePort?WSDL",
  targetNamespace="http://file.integration.eq/", name="QFEQIFFileLockingServiceService")
public class QFEQIFFileLockingServiceService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
        String configFile = System.getenv("QFEQIF_CONFIG");
        Properties pro = new Properties();
        pro.load(new FileInputStream(configFile));
        
      logger = Logger.getLogger("qantas.integration.util.wsclient.QFEQIFFileLockingServiceService");
      URL baseUrl = QFEQIFFileLockingServiceService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            QFEQIFFileLockingServiceService.class.getResource(pro.getProperty("FILE_LOCKING_URL"));
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, pro.getProperty("FILE_LOCKING_URL"));
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, pro.getProperty("FILE_LOCKING_URL"));
      }
    }
    catch (Exception e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://172.27.45.4:16035/IHubFileMgmt/QFEQIFFileLockingServicePort?WSDL",
          e);
    }
  }

  public QFEQIFFileLockingServiceService()
  {
    super(wsdlLocationURL,
          new QName("http://file.integration.eq/", "QFEQIFFileLockingServiceService"));
  }

  public QFEQIFFileLockingServiceService(URL wsdlLocation,
                                         QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="QFEQIFFileLockingServicePort")
  public qantas.integration.util.wsclient.QFEQIFFileLockingService getQFEQIFFileLockingServicePort()
  {
    return (qantas.integration.util.wsclient.QFEQIFFileLockingService) super.getPort(new QName("http://file.integration.eq/",
                                                                                               "QFEQIFFileLockingServicePort"),
                                                                                     qantas.integration.util.wsclient.QFEQIFFileLockingService.class);
  }

  @WebEndpoint(name="QFEQIFFileLockingServicePort")
  public qantas.integration.util.wsclient.QFEQIFFileLockingService getQFEQIFFileLockingServicePort(WebServiceFeature... features)
  {
    return (qantas.integration.util.wsclient.QFEQIFFileLockingService) super.getPort(new QName("http://file.integration.eq/",
                                                                                               "QFEQIFFileLockingServicePort"),
                                                                                     qantas.integration.util.wsclient.QFEQIFFileLockingService.class,
                                                                                     features);
  }
}
