package qantas.integration.util.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://eqdev-soa.qantas.com.au:16015/IHubFileMgmt/QFEQIFFileLockingServicePort?WSDL",
  targetNamespace="http://file.integration.eq/", name="QFEQIFFileLockingService")
@XmlSeeAlso(
  { qantas.integration.util.genJava.ObjectFactory.class })
public interface QFEQIFFileLockingService
{
  @WebMethod
  @Action(input="http://file.integration.eq/QFEQIFFileLockingService/getLockRequest",
    output="http://file.integration.eq/QFEQIFFileLockingService/getLockResponse")
  @ResponseWrapper(localName="getLockResponse", targetNamespace="http://file.integration.eq/",
    className="qantas.integration.util.genJava.GetLockResponse")
  @RequestWrapper(localName="getLock", targetNamespace="http://file.integration.eq/",
    className="qantas.integration.util.genJava.GetLock")
  @WebResult(targetNamespace="")
  public boolean getLock(@WebParam(targetNamespace="", name="arg0")
    String arg0, @WebParam(targetNamespace="", name="arg1")
    String arg1);

  @WebMethod
  @Action(input="http://file.integration.eq/QFEQIFFileLockingService/releaseLockRequest",
    output="http://file.integration.eq/QFEQIFFileLockingService/releaseLockResponse")
  @ResponseWrapper(localName="releaseLockResponse", targetNamespace="http://file.integration.eq/",
    className="qantas.integration.util.genJava.ReleaseLockResponse")
  @RequestWrapper(localName="releaseLock", targetNamespace="http://file.integration.eq/",
    className="qantas.integration.util.genJava.ReleaseLock")
  public void releaseLock(@WebParam(targetNamespace="", name="arg0")
    String arg0, @WebParam(targetNamespace="", name="arg1")
    String arg1, @WebParam(targetNamespace="", name="arg2")
    String arg2);
}
